const fb = {
  viet:    "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
  machine: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80",
  tea:     "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80",
  juice:   "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600&q=80",
  yogurt:  "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80",
  matcha:  "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&q=80",
  smoothie:"https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&q=80",
};

export const drinks = [
  // ── Cà phê máy ─────────────────────────────────────────────────────────────
  {
    id: "americano",
    name: "Americano",
    tag: "Cà phê máy",
    price: 35000,
    calories: 10,
    time: "5 phút",
    rating: 4.5,
    description: "Espresso pha loãng với nước nóng, vị đậm đà thanh hơn espresso nguyên chất.",
    ingredients: ["Espresso", "Nước nóng", "Đá (iced)"],
    image: "/images/americano.jpg",
    fallbackImage: fb.machine,
  },
  {
    id: "cappuccino",
    name: "Cappuccino",
    tag: "Cà phê máy",
    price: 65000,
    calories: 100,
    time: "6 phút",
    rating: 4.6,
    description: "Espresso kết hợp steamed milk và foam sữa dày mịn — lớp bọt sữa đặc trưng không thể nhầm.",
    ingredients: ["Espresso", "Steamed milk", "Milk foam"],
    image: "/images/cappuccino.jpg",
    fallbackImage: fb.machine,
  },
  {
    id: "espresso",
    name: "Espresso",
    tag: "Cà phê máy",
    price: 30000,
    calories: 5,
    time: "3 phút",
    rating: 4.5,
    description: "Cà phê chiết xuất áp suất cao, đậm đặc và mạnh mẽ — nền tảng của mọi thức uống cà phê.",
    ingredients: ["Hạt cà phê rang đậm", "Nước nóng áp suất cao"],
    image: "/images/espresso.jpg",
    fallbackImage: fb.machine,
  },
  {
    id: "latte",
    name: "Latte",
    tag: "Cà phê máy",
    price: 65000,
    calories: 130,
    time: "6 phút",
    rating: 4.7,
    description: "Espresso hòa quyện cùng steamed milk tỷ lệ nhiều, vị béo nhẹ nhàng với latte art đẹp mắt.",
    ingredients: ["Espresso", "Steamed milk", "Milk foam mỏng"],
    image: "/images/latte.jpg",
    fallbackImage: fb.machine,
  },

  // ── Cà phê Việt ────────────────────────────────────────────────────────────
  {
    id: "bac-xiu",
    name: "Bạc xỉu",
    tag: "Cà phê Việt",
    price: 30000,
    calories: 120,
    time: "5 phút",
    rating: 4.7,
    description: "Cà phê sữa tỷ lệ sữa nhiều hơn cà phê, vị ngọt nhẹ thơm béo — phiên bản dịu dàng.",
    ingredients: ["Cà phê", "Sữa đặc", "Sữa tươi", "Đá"],
    image: "/images/bac-xiu.jpg",
    fallbackImage: fb.viet,
  },
  {
    id: "ca-phe-den-da",
    name: "Đen đá",
    tag: "Cà phê Việt",
    price: 25000,
    calories: 10,
    time: "5 phút",
    rating: 4.6,
    description: "Cà phê phin robusta đậm đà, nhỏ chậm qua phin rồi đổ lên đá lạnh — sảng khoái tức thì.",
    ingredients: ["Cà phê robusta", "Đá", "Đường (tùy chọn)"],
    image: "/images/ca-phe-den-da.jpg",
    fallbackImage: fb.viet,
  },
  {
    id: "ca-phe-dua",
    name: "Cà phê cốt dừa",
    tag: "Cà phê Việt",
    price: 45000,
    calories: 180,
    time: "7 phút",
    rating: 4.8,
    description: "Cà phê phin hoà quyện cùng cốt dừa béo ngậy xay nhuyễn, thơm dừa lan toả từng ngụm.",
    ingredients: ["Cà phê phin", "Cốt dừa", "Sữa đặc", "Đá xay"],
    image: "/images/ca-phe-dua.jpg",
    fallbackImage: fb.viet,
  },
  {
    id: "ca-phe-sua-da",
    name: "Nâu đá",
    tag: "Cà phê Việt",
    price: 30000,
    calories: 150,
    time: "5 phút",
    rating: 4.9,
    description: "Cà phê phin pha sữa đặc ngọt bùi, đổ đá lạnh — thức uống quốc dân số một Việt Nam.",
    ingredients: ["Cà phê phin", "Sữa đặc", "Đá"],
    image: "/images/ca-phe-sua-da.jpg",
    fallbackImage: fb.viet,
  },
  {
    id: "ca-phe-trung",
    name: "Cà phê trứng",
    tag: "Cà phê Việt",
    price: 45000,
    calories: 200,
    time: "8 phút",
    rating: 4.8,
    description: "Cà phê đen mạnh phủ lớp kem trứng đánh bông mịn ngọt ngào — đặc sản Hà Nội trứ danh.",
    ingredients: ["Cà phê đen", "Lòng đỏ trứng", "Sữa đặc", "Đường"],
    image: "/images/ca-phe-trung.jpg",
    fallbackImage: fb.viet,
  },

  // ── Matcha ─────────────────────────────────────────────────────────────────
  {
    id: "matcha-latte-nong",
    name: "Matcha latte",
    tag: "Matcha",
    price: 60000,
    calories: 180,
    time: "6 phút",
    rating: 4.7,
    description: "Matcha cấp độ ceremonial hoà với steamed milk béo mịn, ấm áp và thanh đắng dịu.",
    ingredients: ["Matcha ceremonial", "Steamed milk", "Mật ong (tùy chọn)"],
    image: "/images/matcha-latte-nong.jpg",
    fallbackImage: fb.matcha,
  },
  {
    id: "matcha-sua-da",
    name: "Matcha sữa đá",
    tag: "Matcha",
    price: 55000,
    calories: 160,
    time: "5 phút",
    rating: 4.7,
    description: "Matcha culinary pha sữa đặc và sữa tươi, đổ đá lạnh — vị ngọt bùi xen chút đắng thanh.",
    ingredients: ["Matcha culinary", "Sữa tươi", "Sữa đặc", "Đá"],
    image: "/images/matcha-sua-da.jpg",
    fallbackImage: fb.matcha,
  },

  // ── Nước ép ────────────────────────────────────────────────────────────────
  {
    id: "nuoc-cam-ep",
    name: "Nước cam ép",
    tag: "Nước ép",
    price: 40000,
    calories: 90,
    time: "5 phút",
    rating: 4.5,
    description: "Cam tươi ép nguyên chất không pha loãng, ngọt chua tự nhiên giàu vitamin C.",
    ingredients: ["Cam tươi", "Đá", "Đường (tùy chọn)"],
    image: "/images/nuoc-cam-ep.jpg",
    fallbackImage: fb.juice,
  },
  {
    id: "nuoc-chanh-muoi",
    name: "Nước chanh",
    tag: "Nước ép",
    price: 25000,
    calories: 40,
    time: "3 phút",
    rating: 4.4,
    description: "Chanh vắt tươi nguyên chất, chua thanh tự nhiên — giải khát nhanh gọn và dễ chịu.",
    ingredients: ["Chanh tươi", "Đường", "Đá", "Soda (tùy chọn)"],
    image: "/images/nuoc-chanh-muoi.jpg",
    fallbackImage: fb.juice,
  },
  {
    id: "nuoc-dua",
    name: "Nước dừa",
    tag: "Nước ép",
    price: 40000,
    calories: 60,
    time: "2 phút",
    rating: 4.6,
    description: "Nước dừa tươi nguyên trái, ngọt thanh tự nhiên, bổ điện giải và cực kỳ giải nhiệt.",
    ingredients: ["Dừa tươi", "Đá"],
    image: "/images/nuoc-dua.jpg",
    fallbackImage: fb.juice,
  },
  {
    id: "nuoc-mia",
    name: "Nước mía",
    tag: "Nước ép",
    price: 20000,
    calories: 100,
    time: "3 phút",
    rating: 4.5,
    description: "Mía ép tươi nguyên chất vắt thêm chút tắc, ngọt mát giải nhiệt ngay lập tức.",
    ingredients: ["Mía", "Tắc (quất)", "Đá"],
    image: "/images/nuoc-mia.jpg",
    fallbackImage: fb.juice,
  },

  // ── Sinh tố ────────────────────────────────────────────────────────────────
  {
    id: "sinh-to-bo",
    name: "Sinh tố bơ",
    tag: "Sinh tố",
    price: 45000,
    calories: 280,
    time: "5 phút",
    rating: 4.7,
    description: "Bơ chín xay mịn cùng sữa đặc và sữa tươi, sánh béo ngậy bổ dưỡng.",
    ingredients: ["Bơ", "Sữa đặc", "Sữa tươi", "Đá"],
    image: "/images/sinh-to-bo.jpg",
    fallbackImage: fb.smoothie,
  },
  {
    id: "sinh-to-dau-tay",
    name: "Sinh tố dâu tây",
    tag: "Sinh tố",
    price: 45000,
    calories: 150,
    time: "5 phút",
    rating: 4.6,
    description: "Dâu tây Đà Lạt tươi xay cùng sữa chua và sữa tươi, màu hồng đẹp mắt vị chua ngọt.",
    ingredients: ["Dâu tây", "Sữa chua", "Sữa tươi", "Đá", "Đường"],
    image: "/images/sinh-to-dau-tay.jpg",
    fallbackImage: fb.smoothie,
  },
  {
    id: "sinh-to-xoai",
    name: "Sinh tố xoài",
    tag: "Sinh tố",
    price: 40000,
    calories: 180,
    time: "5 phút",
    rating: 4.7,
    description: "Xoài cát chín mọng xay nhuyễn cùng sữa đặc, màu vàng rực thơm ngào ngạt.",
    ingredients: ["Xoài cát", "Sữa đặc", "Sữa tươi", "Đá"],
    image: "/images/sinh-to-xoai.jpg",
    fallbackImage: fb.smoothie,
  },

  // ── Sữa chua ───────────────────────────────────────────────────────────────
  {
    id: "sua-chua-xoai",
    name: "Sữa chua xoài",
    tag: "Sữa chua",
    price: 40000,
    calories: 160,
    time: "3 phút",
    rating: 4.6,
    description: "Sữa chua dẻo mịn blend cùng xoài cát chín ngọt, vị chua ngọt hài hòa mát lạnh.",
    ingredients: ["Sữa chua", "Xoài cát", "Đường", "Đá"],
    image: "/images/sua-chua-xoai.jpg",
    fallbackImage: fb.yogurt,
  },

  // ── Trà ────────────────────────────────────────────────────────────────────
  {
    id: "tra-dao-cam-sa",
    name: "Trà đào cam sả",
    tag: "Trà",
    price: 45000,
    calories: 120,
    time: "5 phút",
    rating: 4.8,
    description: "Trà xanh pha đào mật ngọt, thêm cam và sả tươi thơm mát — đẹp mắt và cực hot.",
    ingredients: ["Trà xanh", "Đào mật", "Cam", "Sả", "Đường", "Đá"],
    image: "/images/tra-dao-cam-sa.jpg",
    fallbackImage: fb.tea,
  },
  {
    id: "tra-o-long-sua",
    name: "Trà ô long sữa",
    tag: "Trà",
    price: 50000,
    calories: 160,
    time: "5 phút",
    rating: 4.6,
    description: "Trà ô long thượng hạng ủ đậm pha cùng sữa tươi béo mịn, hậu vị ngọt ngào khó quên.",
    ingredients: ["Trà ô long", "Sữa tươi", "Đường", "Đá"],
    image: "/images/tra-o-long-sua.jpg",
    fallbackImage: fb.tea,
  },
];
