const fb = {
  viet:    "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
  machine: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80",
  tea:     "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80",
  juice:   "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600&q=80",
  yogurt:  "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80",
  matcha:  "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&q=80",
  smoothie:"https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&q=80",
};

export const drinks = [
  // â”€â”€ CÃ  phÃª mÃ¡y â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "americano",
    name: "Americano",
    tag: "CÃ  phÃª mÃ¡y",
    price: 35000,
    calories: 10,
    time: "5 phÃºt",
    rating: 4.5,
    description: "Espresso pha loÃ£ng vá»›i nÆ°á»›c nÃ³ng, vá»‹ Ä‘áº­m Ä‘Ã  thanh hÆ¡n espresso nguyÃªn cháº¥t.",
    ingredients: ["Espresso", "NÆ°á»›c nÃ³ng", "ÄÃ¡ (iced)"],
    image: "/images/drinks/americano.jpg",
    fallbackImage: fb.machine,
  },
  {
    id: "cappuccino",
    name: "Cappuccino",
    tag: "CÃ  phÃª mÃ¡y",
    price: 65000,
    calories: 100,
    time: "6 phÃºt",
    rating: 4.6,
    description: "Espresso káº¿t há»£p steamed milk vÃ  foam sá»¯a dÃ y má»‹n â€” lá»›p bá»t sá»¯a Ä‘áº·c trÆ°ng khÃ´ng thá»ƒ nháº§m.",
    ingredients: ["Espresso", "Steamed milk", "Milk foam"],
    image: "/images/drinks/cappuccino.jpg",
    fallbackImage: fb.machine,
  },
  {
    id: "espresso",
    name: "Espresso",
    tag: "CÃ  phÃª mÃ¡y",
    price: 30000,
    calories: 5,
    time: "3 phÃºt",
    rating: 4.5,
    description: "CÃ  phÃª chiáº¿t xuáº¥t Ã¡p suáº¥t cao, Ä‘áº­m Ä‘áº·c vÃ  máº¡nh máº½ â€” ná»n táº£ng cá»§a má»i thá»©c uá»‘ng cÃ  phÃª.",
    ingredients: ["Háº¡t cÃ  phÃª rang Ä‘áº­m", "NÆ°á»›c nÃ³ng Ã¡p suáº¥t cao"],
    image: "/images/drinks/espresso.jpg",
    fallbackImage: fb.machine,
  },
  {
    id: "latte",
    name: "Latte",
    tag: "CÃ  phÃª mÃ¡y",
    price: 65000,
    calories: 130,
    time: "6 phÃºt",
    rating: 4.7,
    description: "Espresso hÃ²a quyá»‡n cÃ¹ng steamed milk tá»· lá»‡ nhiá»u, vá»‹ bÃ©o nháº¹ nhÃ ng vá»›i latte art Ä‘áº¹p máº¯t.",
    ingredients: ["Espresso", "Steamed milk", "Milk foam má»ng"],
    image: "/images/drinks/latte.jpg",
    fallbackImage: fb.machine,
  },

  // â”€â”€ CÃ  phÃª Viá»‡t â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "bac-xiu",
    name: "Báº¡c xá»‰u",
    tag: "CÃ  phÃª Viá»‡t",
    price: 30000,
    calories: 120,
    time: "5 phÃºt",
    rating: 4.7,
    description: "CÃ  phÃª sá»¯a tá»· lá»‡ sá»¯a nhiá»u hÆ¡n cÃ  phÃª, vá»‹ ngá»t nháº¹ thÆ¡m bÃ©o â€” phiÃªn báº£n dá»‹u dÃ ng.",
    ingredients: ["CÃ  phÃª", "Sá»¯a Ä‘áº·c", "Sá»¯a tÆ°Æ¡i", "ÄÃ¡"],
    image: "/images/drinks/bac-xiu.jpg",
    fallbackImage: fb.viet,
  },
  {
    id: "ca-phe-den-da",
    name: "Äen Ä‘Ã¡",
    tag: "CÃ  phÃª Viá»‡t",
    price: 25000,
    calories: 10,
    time: "5 phÃºt",
    rating: 4.6,
    description: "CÃ  phÃª phin robusta Ä‘áº­m Ä‘Ã , nhá» cháº­m qua phin rá»“i Ä‘á»• lÃªn Ä‘Ã¡ láº¡nh â€” sáº£ng khoÃ¡i tá»©c thÃ¬.",
    ingredients: ["CÃ  phÃª robusta", "ÄÃ¡", "ÄÆ°á»ng (tÃ¹y chá»n)"],
    image: "/images/drinks/ca-phe-den-da.jpg",
    fallbackImage: fb.viet,
  },
  {
    id: "ca-phe-dua",
    name: "CÃ  phÃª cá»‘t dá»«a",
    tag: "CÃ  phÃª Viá»‡t",
    price: 45000,
    calories: 180,
    time: "7 phÃºt",
    rating: 4.8,
    description: "CÃ  phÃª phin hoÃ  quyá»‡n cÃ¹ng cá»‘t dá»«a bÃ©o ngáº­y xay nhuyá»…n, thÆ¡m dá»«a lan toáº£ tá»«ng ngá»¥m.",
    ingredients: ["CÃ  phÃª phin", "Cá»‘t dá»«a", "Sá»¯a Ä‘áº·c", "ÄÃ¡ xay"],
    image: "/images/drinks/ca-phe-dua.jpg",
    fallbackImage: fb.viet,
  },
  {
    id: "ca-phe-sua-da",
    name: "NÃ¢u Ä‘Ã¡",
    tag: "CÃ  phÃª Viá»‡t",
    price: 30000,
    calories: 150,
    time: "5 phÃºt",
    rating: 4.9,
    description: "CÃ  phÃª phin pha sá»¯a Ä‘áº·c ngá»t bÃ¹i, Ä‘á»• Ä‘Ã¡ láº¡nh â€” thá»©c uá»‘ng quá»‘c dÃ¢n sá»‘ má»™t Viá»‡t Nam.",
    ingredients: ["CÃ  phÃª phin", "Sá»¯a Ä‘áº·c", "ÄÃ¡"],
    image: "/images/drinks/ca-phe-sua-da.jpg",
    fallbackImage: fb.viet,
  },
  {
    id: "ca-phe-trung",
    name: "CÃ  phÃª trá»©ng",
    tag: "CÃ  phÃª Viá»‡t",
    price: 45000,
    calories: 200,
    time: "8 phÃºt",
    rating: 4.8,
    description: "CÃ  phÃª Ä‘en máº¡nh phá»§ lá»›p kem trá»©ng Ä‘Ã¡nh bÃ´ng má»‹n ngá»t ngÃ o â€” Ä‘áº·c sáº£n HÃ  Ná»™i trá»© danh.",
    ingredients: ["CÃ  phÃª Ä‘en", "LÃ²ng Ä‘á» trá»©ng", "Sá»¯a Ä‘áº·c", "ÄÆ°á»ng"],
    image: "/images/drinks/ca-phe-trung.jpg",
    fallbackImage: fb.viet,
  },

  // â”€â”€ Matcha â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "matcha-latte-nong",
    name: "Matcha latte",
    tag: "Matcha",
    price: 60000,
    calories: 180,
    time: "6 phÃºt",
    rating: 4.7,
    description: "Matcha cáº¥p Ä‘á»™ ceremonial hoÃ  vá»›i steamed milk bÃ©o má»‹n, áº¥m Ã¡p vÃ  thanh Ä‘áº¯ng dá»‹u.",
    ingredients: ["Matcha ceremonial", "Steamed milk", "Máº­t ong (tÃ¹y chá»n)"],
    image: "/images/drinks/matcha-latte-nong.jpg",
    fallbackImage: fb.matcha,
  },
  {
    id: "matcha-sua-da",
    name: "Matcha sá»¯a Ä‘Ã¡",
    tag: "Matcha",
    price: 55000,
    calories: 160,
    time: "5 phÃºt",
    rating: 4.7,
    description: "Matcha culinary pha sá»¯a Ä‘áº·c vÃ  sá»¯a tÆ°Æ¡i, Ä‘á»• Ä‘Ã¡ láº¡nh â€” vá»‹ ngá»t bÃ¹i xen chÃºt Ä‘áº¯ng thanh.",
    ingredients: ["Matcha culinary", "Sá»¯a tÆ°Æ¡i", "Sá»¯a Ä‘áº·c", "ÄÃ¡"],
    image: "/images/drinks/matcha-sua-da.jpg",
    fallbackImage: fb.matcha,
  },

  // â”€â”€ NÆ°á»›c Ã©p â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "nuoc-cam-ep",
    name: "NÆ°á»›c cam Ã©p",
    tag: "NÆ°á»›c Ã©p",
    price: 40000,
    calories: 90,
    time: "5 phÃºt",
    rating: 4.5,
    description: "Cam tÆ°Æ¡i Ã©p nguyÃªn cháº¥t khÃ´ng pha loÃ£ng, ngá»t chua tá»± nhiÃªn giÃ u vitamin C.",
    ingredients: ["Cam tÆ°Æ¡i", "ÄÃ¡", "ÄÆ°á»ng (tÃ¹y chá»n)"],
    image: "/images/drinks/nuoc-cam-ep.jpg",
    fallbackImage: fb.juice,
  },
  {
    id: "nuoc-chanh-muoi",
    name: "NÆ°á»›c chanh",
    tag: "NÆ°á»›c Ã©p",
    price: 25000,
    calories: 40,
    time: "3 phÃºt",
    rating: 4.4,
    description: "Chanh váº¯t tÆ°Æ¡i nguyÃªn cháº¥t, chua thanh tá»± nhiÃªn â€” giáº£i khÃ¡t nhanh gá»n vÃ  dá»… chá»‹u.",
    ingredients: ["Chanh tÆ°Æ¡i", "ÄÆ°á»ng", "ÄÃ¡", "Soda (tÃ¹y chá»n)"],
    image: "/images/drinks/nuoc-chanh-muoi.jpg",
    fallbackImage: fb.juice,
  },
  {
    id: "nuoc-dua",
    name: "NÆ°á»›c dá»«a",
    tag: "NÆ°á»›c Ã©p",
    price: 40000,
    calories: 60,
    time: "2 phÃºt",
    rating: 4.6,
    description: "NÆ°á»›c dá»«a tÆ°Æ¡i nguyÃªn trÃ¡i, ngá»t thanh tá»± nhiÃªn, bá»• Ä‘iá»‡n giáº£i vÃ  cá»±c ká»³ giáº£i nhiá»‡t.",
    ingredients: ["Dá»«a tÆ°Æ¡i", "ÄÃ¡"],
    image: "/images/drinks/nuoc-dua.jpg",
    fallbackImage: fb.juice,
  },
  {
    id: "nuoc-mia",
    name: "NÆ°á»›c mÃ­a",
    tag: "NÆ°á»›c Ã©p",
    price: 20000,
    calories: 100,
    time: "3 phÃºt",
    rating: 4.5,
    description: "MÃ­a Ã©p tÆ°Æ¡i nguyÃªn cháº¥t váº¯t thÃªm chÃºt táº¯c, ngá»t mÃ¡t giáº£i nhiá»‡t ngay láº­p tá»©c.",
    ingredients: ["MÃ­a", "Táº¯c (quáº¥t)", "ÄÃ¡"],
    image: "/images/drinks/nuoc-mia.jpg",
    fallbackImage: fb.juice,
  },

  // â”€â”€ Sinh tá»‘ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "sinh-to-bo",
    name: "Sinh tá»‘ bÆ¡",
    tag: "Sinh tá»‘",
    price: 45000,
    calories: 280,
    time: "5 phÃºt",
    rating: 4.7,
    description: "BÆ¡ chÃ­n xay má»‹n cÃ¹ng sá»¯a Ä‘áº·c vÃ  sá»¯a tÆ°Æ¡i, sÃ¡nh bÃ©o ngáº­y bá»• dÆ°á»¡ng.",
    ingredients: ["BÆ¡", "Sá»¯a Ä‘áº·c", "Sá»¯a tÆ°Æ¡i", "ÄÃ¡"],
    image: "/images/drinks/sinh-to-bo.jpg",
    fallbackImage: fb.smoothie,
  },
  {
    id: "sinh-to-dau-tay",
    name: "Sinh tá»‘ dÃ¢u tÃ¢y",
    tag: "Sinh tá»‘",
    price: 45000,
    calories: 150,
    time: "5 phÃºt",
    rating: 4.6,
    description: "DÃ¢u tÃ¢y ÄÃ  Láº¡t tÆ°Æ¡i xay cÃ¹ng sá»¯a chua vÃ  sá»¯a tÆ°Æ¡i, mÃ u há»“ng Ä‘áº¹p máº¯t vá»‹ chua ngá»t.",
    ingredients: ["DÃ¢u tÃ¢y", "Sá»¯a chua", "Sá»¯a tÆ°Æ¡i", "ÄÃ¡", "ÄÆ°á»ng"],
    image: "/images/drinks/sinh-to-dau-tay.jpg",
    fallbackImage: fb.smoothie,
  },
  {
    id: "sinh-to-xoai",
    name: "Sinh tá»‘ xoÃ i",
    tag: "Sinh tá»‘",
    price: 40000,
    calories: 180,
    time: "5 phÃºt",
    rating: 4.7,
    description: "XoÃ i cÃ¡t chÃ­n má»ng xay nhuyá»…n cÃ¹ng sá»¯a Ä‘áº·c, mÃ u vÃ ng rá»±c thÆ¡m ngÃ o ngáº¡t.",
    ingredients: ["XoÃ i cÃ¡t", "Sá»¯a Ä‘áº·c", "Sá»¯a tÆ°Æ¡i", "ÄÃ¡"],
    image: "/images/drinks/sinh-to-xoai.jpg",
    fallbackImage: fb.smoothie,
  },

  // â”€â”€ Sá»¯a chua â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "sua-chua-xoai",
    name: "Sá»¯a chua xoÃ i",
    tag: "Sá»¯a chua",
    price: 40000,
    calories: 160,
    time: "3 phÃºt",
    rating: 4.6,
    description: "Sá»¯a chua dáº»o má»‹n blend cÃ¹ng xoÃ i cÃ¡t chÃ­n ngá»t, vá»‹ chua ngá»t hÃ i hÃ²a mÃ¡t láº¡nh.",
    ingredients: ["Sá»¯a chua", "XoÃ i cÃ¡t", "ÄÆ°á»ng", "ÄÃ¡"],
    image: "/images/drinks/sua-chua-xoai.jpg",
    fallbackImage: fb.yogurt,
  },

  // â”€â”€ TrÃ  â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "tra-dao-cam-sa",
    name: "TrÃ  Ä‘Ã o cam sáº£",
    tag: "TrÃ ",
    price: 45000,
    calories: 120,
    time: "5 phÃºt",
    rating: 4.8,
    description: "TrÃ  xanh pha Ä‘Ã o máº­t ngá»t, thÃªm cam vÃ  sáº£ tÆ°Æ¡i thÆ¡m mÃ¡t â€” Ä‘áº¹p máº¯t vÃ  cá»±c hot.",
    ingredients: ["TrÃ  xanh", "ÄÃ o máº­t", "Cam", "Sáº£", "ÄÆ°á»ng", "ÄÃ¡"],
    image: "/images/drinks/tra-dao-cam-sa.jpg",
    fallbackImage: fb.tea,
  },
  {
    id: "tra-o-long-sua",
    name: "TrÃ  Ã´ long sá»¯a",
    tag: "TrÃ ",
    price: 50000,
    calories: 160,
    time: "5 phÃºt",
    rating: 4.6,
    description: "TrÃ  Ã´ long thÆ°á»£ng háº¡ng á»§ Ä‘áº­m pha cÃ¹ng sá»¯a tÆ°Æ¡i bÃ©o má»‹n, háº­u vá»‹ ngá»t ngÃ o khÃ³ quÃªn.",
    ingredients: ["TrÃ  Ã´ long", "Sá»¯a tÆ°Æ¡i", "ÄÆ°á»ng", "ÄÃ¡"],
    image: "/images/drinks/tra-o-long-sua.jpg",
    fallbackImage: fb.tea,
  },
];

