const fb = {
  coffee: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
  tea: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80",
  smoothie: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&q=80",
  juice: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600&q=80",
};

export const drinks = [
  {
    id: "bac-xiu",
    name: "Bạc xỉu",
    tag: "Cà phê",
    price: 30000,
    calories: 120,
    time: "5 phút",
    rating: 4.7,
    description: "Cà phê sữa tỷ lệ sữa nhiều hơn cà phê, vị ngọt nhẹ thơm béo — phiên bản dịu dàng của cà phê sữa đá.",
    ingredients: ["Cà phê", "Sữa đặc", "Sữa tươi", "Đá"],
    image: "/images/bac-xiu.jpg",
    fallbackImage: fb.coffee,
  },
  {
    id: "ca-phe-den-da",
    name: "Cà phê đen đá",
    tag: "Cà phê",
    price: 25000,
    calories: 10,
    time: "5 phút",
    rating: 4.6,
    description: "Cà phê phin robusta đậm đà, nhỏ chậm qua phin rồi đổ lên đá lạnh — sảng khoái tức thì.",
    ingredients: ["Cà phê robusta", "Đá", "Đường (tùy chọn)"],
    image: "/images/ca-phe-den-da.jpg",
    fallbackImage: fb.coffee,
  },
  {
    id: "ca-phe-sua-da",
    name: "Cà phê sữa đá",
    tag: "Cà phê",
    price: 30000,
    calories: 150,
    time: "5 phút",
    rating: 4.9,
    description: "Cà phê phin pha sữa đặc ngọt bùi, đổ đá lạnh — thức uống quốc dân số một của Việt Nam.",
    ingredients: ["Cà phê phin", "Sữa đặc", "Đá"],
    image: "/images/ca-phe-sua-da.jpg",
    fallbackImage: fb.coffee,
  },
  {
    id: "hong-tra-sua",
    name: "Hồng trà sữa",
    tag: "Trà",
    price: 45000,
    calories: 200,
    time: "5 phút",
    rating: 4.5,
    description: "Trà đen pha sữa tươi thơm béo, thêm trân châu dai giòn — kéo dài cả buổi chiều.",
    ingredients: ["Hồng trà", "Sữa tươi", "Trân châu", "Đường"],
    image: "/images/hong-tra-sua.jpg",
    fallbackImage: fb.tea,
  },
  {
    id: "nuoc-chanh-muoi",
    name: "Nước chanh muối",
    tag: "Giải khát",
    price: 25000,
    calories: 40,
    time: "3 phút",
    rating: 4.4,
    description: "Chanh vắt với muối ớt, vừa chua vừa mặn mặn — giải khát cực đỉnh những ngày hè oi bức.",
    ingredients: ["Chanh tươi", "Muối", "Đường", "Đá"],
    image: "/images/nuoc-chanh-muoi.jpg",
    fallbackImage: fb.juice,
  },
  {
    id: "nuoc-dua",
    name: "Nước dừa",
    tag: "Giải khát",
    price: 25000,
    calories: 60,
    time: "2 phút",
    rating: 4.6,
    description: "Nước dừa tươi nguyên trái, ngọt thanh tự nhiên, bổ điện giải và cực kỳ giải nhiệt.",
    ingredients: ["Dừa tươi", "Đá"],
    image: "/images/nuoc-dua.jpg",
    fallbackImage: fb.juice,
  },
  {
    id: "nuoc-mia",
    name: "Nước mía",
    tag: "Giải khát",
    price: 20000,
    calories: 100,
    time: "3 phút",
    rating: 4.5,
    description: "Mía ép tươi nguyên chất vắt thêm chút tắc, ngọt mát giải nhiệt ngay lập tức.",
    ingredients: ["Mía", "Tắc (quất)", "Đá"],
    image: "/images/nuoc-mia.jpg",
    fallbackImage: fb.juice,
  },
  {
    id: "sinh-to-bo",
    name: "Sinh tố bơ",
    tag: "Giải khát",
    price: 45000,
    calories: 280,
    time: "5 phút",
    rating: 4.7,
    description: "Bơ chín xay mịn cùng sữa đặc và sữa tươi, sánh béo ngậy bổ dưỡng — ăn sáng thay cũng được.",
    ingredients: ["Bơ", "Sữa đặc", "Sữa tươi", "Đá"],
    image: "/images/sinh-to-bo.jpg",
    fallbackImage: fb.smoothie,
  },
  {
    id: "tra-dao-cam-sa",
    name: "Trà đào cam sả",
    tag: "Trà",
    price: 45000,
    calories: 120,
    time: "5 phút",
    rating: 4.8,
    description: "Trà xanh pha đào mật ngọt, thêm cam và sả tươi thơm mát — đẹp mắt, thơm miệng, cực hot.",
    ingredients: ["Trà xanh", "Đào mật", "Cam", "Sả", "Đường", "Đá"],
    image: "/images/tra-dao-cam-sa.jpg",
    fallbackImage: fb.tea,
  },
  {
    id: "tra-sua-tran-chau",
    name: "Trà sữa trân châu",
    tag: "Trà",
    price: 45000,
    calories: 240,
    time: "5 phút",
    rating: 4.8,
    description: "Trà sữa kinh điển với trân châu đen dai giòn nấu đường nâu — uống một lần là ghiền ngay.",
    ingredients: ["Trà đen", "Sữa tươi", "Trân châu đen", "Đường nâu"],
    image: "/images/tra-sua-tran-chau.jpg",
    fallbackImage: fb.tea,
  },
];
