const fallbackImages = {
  noodle:
    "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=1200&q=80",
  rice:
    "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=1200&q=80",
  bread:
    "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=1200&q=80",
  roll:
    "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
  hotpot:
    "https://images.unsplash.com/photo-1617196034183-421b4917c92d?auto=format&fit=crop&w=1200&q=80",
};

export const foods = [
  {
    id: "banh-bao",
    name: "BÃ¡nh bao",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 15000,
    calories: 320,
    time: "5 phÃºt",
    rating: 4.4,
    description: "BÃ¡nh háº¥p nhÃ¢n thá»‹t, trá»©ng cÃºt, miáº¿n vÃ  má»™c nhÄ©.",
    ingredients: ["Bá»™t mÃ¬", "Thá»‹t bÄƒm", "Trá»©ng cÃºt", "Má»™c nhÄ©"],
    image: "/images/foods/banh-bao.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-canh",
    name: "BÃ¡nh canh",
    tag: "SÃ¡ng / TrÆ°a / Tá»‘i",
    price: 32000,
    calories: 540,
    time: "12 phÃºt",
    rating: 4.6,
    description: "Sá»£i bÃ¡nh canh dai má»m, nÆ°á»›c dÃ¹ng sÃ¡nh, thÆ°á»ng Äƒn vá»›i cua, cháº£ cÃ¡ hoáº·c giÃ² heo.",
    ingredients: ["BÃ¡nh canh", "NÆ°á»›c dÃ¹ng", "Cháº£ cÃ¡", "GiÃ² heo"],
    image: "/images/foods/banh-canh.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "banh-chuoi-ngo-khoai",
    name: "BÃ¡nh chuá»‘i / ngÃ´ / khoai",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 10000,
    calories: 200,
    time: "2 phÃºt",
    rating: 4.3,
    description: "BÃ¡nh nÆ°á»›ng hoáº·c háº¥p tá»« chuá»‘i, ngÃ´ hoáº·c khoai â€” dÃ¢n dÃ£, thÆ¡m ngá»t tá»± nhiÃªn.",
    ingredients: ["Chuá»‘i / NgÃ´ / Khoai", "Bá»™t náº¿p", "ÄÆ°á»ng", "Dá»«a"],
    image: "/images/foods/banh-chuoi-ngo-khoai.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-cuon",
    name: "BÃ¡nh cuá»‘n",
    tag: "SÃ¡ng",
    price: 30000,
    calories: 360,
    time: "8 phÃºt",
    rating: 4.6,
    description: "BÃ¡nh bá»™t gáº¡o trÃ¡ng má»ng cuá»‘n nhÃ¢n thá»‹t bÄƒm, má»™c nhÄ©, Äƒn vá»›i nÆ°á»›c máº¯m.",
    ingredients: ["Bá»™t gáº¡o", "Thá»‹t bÄƒm", "Má»™c nhÄ©", "NÆ°á»›c máº¯m"],
    image: "/images/foods/banh-cuon.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-gio-mat-mia",
    name: "BÃ¡nh gio máº­t mÃ­a",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 10000,
    calories: 190,
    time: "3 phÃºt",
    rating: 4.4,
    description: "BÃ¡nh gio trong má»‹n, vá»‹ thanh nháº¹, Äƒn vá»›i máº­t mÃ­a ngá»t thÆ¡m â€” mÃ³n truyá»n thá»‘ng giáº£n dá»‹.",
    ingredients: ["Bá»™t gáº¡o náº¿p tro", "Máº­t mÃ­a", "LÃ¡ chuá»‘i"],
    image: "/images/foods/banh-gio-mat-mia.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-gio",
    name: "BÃ¡nh giÃ²",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 15000,
    calories: 310,
    time: "5 phÃºt",
    rating: 4.5,
    description: "BÃ¡nh bá»™t gáº¡o háº¥p lÃ¡ chuá»‘i, nhÃ¢n thá»‹t bÄƒm, má»™c nhÄ©, Äƒn kÃ¨m cháº£ lá»¥a vÃ  tÆ°Æ¡ng á»›t.",
    ingredients: ["Bá»™t gáº¡o", "Thá»‹t bÄƒm", "Má»™c nhÄ©", "Cháº£ lá»¥a"],
    image: "/images/foods/banh-gio.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-goi",
    name: "BÃ¡nh gá»‘i",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 8000,
    calories: 220,
    time: "3 phÃºt",
    rating: 4.4,
    description: "BÃ¡nh chiÃªn giÃ²n nhÃ¢n thá»‹t, má»™c nhÄ©, miáº¿n vÃ  trá»©ng cÃºt â€” Äƒn váº·t cá»•ng trÆ°á»ng quen thuá»™c.",
    ingredients: ["Bá»™t mÃ¬", "Thá»‹t bÄƒm", "Má»™c nhÄ©", "Miáº¿n"],
    image: "/images/foods/banh-goi.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-khuc",
    name: "BÃ¡nh khÃºc",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 15000,
    calories: 420,
    time: "5 phÃºt",
    rating: 4.5,
    description: "XÃ´i gÃ³i bÃªn ngoÃ i, nhÃ¢n Ä‘áº­u xanh vÃ  thá»‹t má»¡, Ã¡o lá»›p náº¿p dáº»o thÆ¡m mÃ¹i rau khÃºc.",
    ingredients: ["Gáº¡o náº¿p", "Rau khÃºc", "Äáº­u xanh", "Thá»‹t má»¡"],
    image: "/images/foods/banh-khuc.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "banh-mi",
    name: "BÃ¡nh mÃ¬",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 25000,
    calories: 430,
    time: "7 phÃºt",
    rating: 4.8,
    description: "BÃ¡nh mÃ¬ giÃ²n káº¹p pate, thá»‹t, trá»©ng hoáº·c gÃ , thÃªm Ä‘á»“ chua vÃ  rau thÆ¡m.",
    ingredients: ["BÃ¡nh mÃ¬", "Pate", "Thá»‹t", "Äá»“ chua"],
    image: "/images/foods/banh-mi.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-my-chao",
    name: "BÃ¡nh má»³ cháº£o",
    tag: "SÃ¡ng / TrÆ°a",
    price: 40000,
    calories: 620,
    time: "12 phÃºt",
    rating: 4.7,
    description: "Cháº£o gang nÃ³ng há»•i vá»›i bÃ², xÃºc xÃ­ch, trá»©ng á»‘p la, rau vÃ  bÃ¡nh má»³ giÃ²n â€” bá»¯a sÃ¡ng sung tÃºc.",
    ingredients: ["BÃ¡nh má»³", "Thá»‹t bÃ²", "Trá»©ng", "XÃºc xÃ­ch"],
    image: "/images/foods/banh-my-chao.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-my-nem-khoai",
    name: "BÃ¡nh má»³ nem khoai",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 25000,
    calories: 420,
    time: "5 phÃºt",
    rating: 4.5,
    description: "BÃ¡nh má»³ giÃ²n káº¹p nem khoai chiÃªn xÃ¹, sá»‘t tÆ°Æ¡ng á»›t vÃ  mayonnaise â€” combo vá»‰a hÃ¨ hot hit.",
    ingredients: ["BÃ¡nh má»³", "Nem khoai", "TÆ°Æ¡ng á»›t", "Mayonnaise"],
    image: "/images/foods/banh-my-nem-khoai.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-my-tam-giac",
    name: "BÃ¡nh má»³ tam giÃ¡c",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 25000,
    calories: 480,
    time: "5 phÃºt",
    rating: 4.6,
    description: "BÃ¡nh má»³ nÆ°á»›ng hÃ¬nh tam giÃ¡c káº¹p thá»‹t, rau vÃ  sá»‘t â€” nhanh gá»n, Ä‘áº§y Ä‘áº·n cho bá»¯a sÃ¡ng.",
    ingredients: ["BÃ¡nh má»³", "Thá»‹t", "Rau", "Sá»‘t"],
    image: "/images/foods/banh-my-tam-giac.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-ngot",
    name: "BÃ¡nh ngá»t",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 18000,
    calories: 280,
    time: "3 phÃºt",
    rating: 4.3,
    description: "BÃ¡nh ngá»t cÃ¡c loáº¡i: su kem, bÃ¡nh bÃ´ng lan, croissant... nháº¹ nhÃ ng cho bá»¯a sÃ¡ng hoáº·c Äƒn váº·t.",
    ingredients: ["Bá»™t mÃ¬", "Trá»©ng", "BÆ¡", "ÄÆ°á»ng"],
    image: "/images/foods/banh-ngot.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-ran",
    name: "BÃ¡nh rÃ¡n",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 5000,
    calories: 180,
    time: "2 phÃºt",
    rating: 4.2,
    description: "BÃ¡nh rÃ¡n vá»«ng giÃ²n ngoÃ i má»m trong, nhÃ¢n Ä‘áº­u xanh ngá»t bÃ¹i, Äƒn nÃ³ng ráº¥t ngon.",
    ingredients: ["Bá»™t náº¿p", "Äáº­u xanh", "Vá»«ng", "ÄÆ°á»ng"],
    image: "/images/foods/banh-ran.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-tacos",
    name: "BÃ¡nh tacos",
    tag: "TrÆ°a / Tá»‘i / Ä‚n nháº¹",
    price: 25000,
    calories: 420,
    time: "10 phÃºt",
    rating: 4.5,
    description: "Vá» bÃ¡nh tacos giÃ²n hoáº·c má»m nhÃ¢n gÃ /bÃ² xÃ o, báº¯p cáº£i tÃ­m, cÃ  rá»‘t vÃ  sá»‘t cay ngá»t.",
    ingredients: ["Vá» tacos", "Thá»‹t gÃ  / bÃ²", "Báº¯p cáº£i tÃ­m", "Sá»‘t Ä‘áº·c biá»‡t"],
    image: "/images/foods/banh-tacos.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-te",
    name: "BÃ¡nh táº»",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 6000,
    calories: 220,
    time: "3 phÃºt",
    rating: 4.3,
    description: "BÃ¡nh bá»™t gáº¡o táº» gÃ³i lÃ¡ dong, nhÃ¢n thá»‹t má»™c nhÄ©, cháº¥m nÆ°á»›c máº¯m gá»«ng.",
    ingredients: ["Bá»™t gáº¡o táº»", "Thá»‹t heo", "Má»™c nhÄ©", "LÃ¡ dong"],
    image: "/images/foods/banh-te.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-trang-cuon",
    name: "BÃ¡nh trÃ¡ng cuá»™n",
    tag: "TrÆ°a / Ä‚n nháº¹",
    price: 25000,
    calories: 320,
    time: "7 phÃºt",
    rating: 4.6,
    description: "BÃ¡nh trÃ¡ng cuá»™n xoÃ i xanh, tÃ´m khÃ´, sa táº¿, tÆ°Æ¡ng vÃ  cÃ¡c topping chua cay máº·n ngá»t.",
    ingredients: ["BÃ¡nh trÃ¡ng", "XoÃ i xanh", "TÃ´m khÃ´", "Sa táº¿"],
    image: "/images/foods/banh-trang-cuon.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-xeo",
    name: "BÃ¡nh xÃ¨o",
    tag: "TrÆ°a / Tá»‘i",
    price: 38000,
    calories: 640,
    time: "18 phÃºt",
    rating: 4.6,
    description: "BÃ¡nh bá»™t nghá»‡ chiÃªn giÃ²n vá»›i tÃ´m, thá»‹t, giÃ¡, cuá»‘n rau sá»‘ng cháº¥m nÆ°á»›c máº¯m.",
    ingredients: ["Bá»™t gáº¡o", "TÃ´m", "Thá»‹t", "GiÃ¡"],
    image: "/images/foods/banh-xeo.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "bun-bo-hue",
    name: "BÃºn bÃ² Huáº¿",
    tag: "SÃ¡ng / TrÆ°a / Tá»‘i",
    price: 40000,
    calories: 620,
    time: "15 phÃºt",
    rating: 4.9,
    description: "BÃºn nÆ°á»›c Ä‘áº­m vá»‹ miá»n Trung vá»›i bÃ², giÃ² heo, sáº£ vÃ  sa táº¿.",
    ingredients: ["BÃºn", "Thá»‹t bÃ²", "GiÃ² heo", "Sáº£"],
    image: "/images/foods/bun-bo-hue.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-ca",
    name: "BÃºn cÃ¡",
    tag: "SÃ¡ng / TrÆ°a",
    price: 35000,
    calories: 470,
    time: "12 phÃºt",
    rating: 4.5,
    description: "BÃºn nÆ°á»›c vá»›i cÃ¡ chiÃªn hoáº·c cÃ¡ háº¥p, cÃ  chua, thÃ¬ lÃ  vÃ  rau sá»‘ng.",
    ingredients: ["BÃºn", "CÃ¡", "CÃ  chua", "ThÃ¬ lÃ "],
    image: "/images/foods/bun-ca.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-cha",
    name: "BÃºn cháº£ HÃ  Ná»™i",
    tag: "TrÆ°a / Tá»‘i",
    price: 40000,
    calories: 610,
    time: "15 phÃºt",
    rating: 4.8,
    description: "BÃºn tÆ°Æ¡i Äƒn vá»›i cháº£ nÆ°á»›ng, thá»‹t nÆ°á»›ng, nÆ°á»›c cháº¥m vÃ  rau sá»‘ng.",
    ingredients: ["BÃºn", "Cháº£ nÆ°á»›ng", "Thá»‹t nÆ°á»›ng", "Rau sá»‘ng"],
    image: "/images/foods/bun-cha.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-dau-mam-tom",
    name: "BÃºn Ä‘áº­u máº¯m tÃ´m",
    tag: "TrÆ°a / Tá»‘i",
    price: 38000,
    calories: 720,
    time: "12 phÃºt",
    rating: 4.6,
    description: "BÃºn lÃ¡, Ä‘áº­u phá»¥ chiÃªn, thá»‹t luá»™c, cháº£ cá»‘m, rau thÆ¡m vÃ  máº¯m tÃ´m.",
    ingredients: ["BÃºn", "Äáº­u phá»¥", "Thá»‹t luá»™c", "Máº¯m tÃ´m"],
    image: "/images/foods/bun-dau-mam-tom.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-moc-suon",
    name: "BÃºn má»c sÆ°á»n",
    tag: "SÃ¡ng / TrÆ°a / Tá»‘i",
    price: 40000,
    calories: 580,
    time: "15 phÃºt",
    rating: 4.7,
    description: "BÃºn nÆ°á»›c ngá»t xÆ°Æ¡ng, viÃªn má»c thá»‹t, sÆ°á»n non, cháº£ vÃ  hÃ nh lÃ¡ thÆ¡m.",
    ingredients: ["BÃºn", "ViÃªn má»c", "SÆ°á»n non", "Cháº£"],
    image: "/images/foods/bun-moc-suon.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-ngan-nuoc",
    name: "BÃºn ngan nÆ°á»›c",
    tag: "SÃ¡ng / TrÆ°a / Tá»‘i",
    price: 40000,
    calories: 560,
    time: "15 phÃºt",
    rating: 4.7,
    description: "BÃºn ngan nÆ°á»›c dÃ¹ng trong ngá»t, thá»‹t ngan má»m, cháº£, rau thÆ¡m vÃ  hÃ nh phi.",
    ingredients: ["BÃºn", "Thá»‹t ngan", "Cháº£", "HÃ nh phi"],
    image: "/images/foods/bun-ngan-nuoc.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-oc",
    name: "BÃºn á»‘c",
    tag: "SÃ¡ng / TrÆ°a",
    price: 35000,
    calories: 460,
    time: "12 phÃºt",
    rating: 4.5,
    description: "BÃºn nÆ°á»›c vá»‹ chua thanh vá»›i á»‘c, cÃ  chua, rau thÆ¡m vÃ  á»›t chÆ°ng.",
    ingredients: ["BÃºn", "á»c", "CÃ  chua", "Rau thÆ¡m"],
    image: "/images/foods/bun-oc.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-rieu",
    name: "BÃºn riÃªu cua",
    tag: "SÃ¡ng / TrÆ°a",
    price: 35000,
    calories: 500,
    time: "12 phÃºt",
    rating: 4.7,
    description: "BÃºn nÆ°á»›c vá»‹ chua nháº¹, riÃªu cua, cÃ  chua, Ä‘áº­u phá»¥ vÃ  rau sá»‘ng.",
    ingredients: ["BÃºn", "RiÃªu cua", "CÃ  chua", "Äáº­u phá»¥"],
    image: "/images/foods/bun-rieu.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-thit-nuong",
    name: "BÃºn thá»‹t nÆ°á»›ng",
    tag: "TrÆ°a / Tá»‘i",
    price: 35000,
    calories: 590,
    time: "12 phÃºt",
    rating: 4.7,
    description: "BÃºn khÃ´ Äƒn vá»›i thá»‹t nÆ°á»›ng, rau, Ä‘á»“ chua, Ä‘áº­u phá»™ng vÃ  nÆ°á»›c máº¯m.",
    ingredients: ["BÃºn", "Thá»‹t nÆ°á»›ng", "Rau", "Äáº­u phá»™ng"],
    image: "/images/foods/bun-thit-nuong.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "ca-kho-to",
    name: "CÃ¡ kho tá»™",
    tag: "TrÆ°a / Tá»‘i",
    price: 45000,
    calories: 560,
    time: "20 phÃºt",
    rating: 4.7,
    description: "CÃ¡ kho nÆ°á»›c mÃ u Ä‘áº­m, vá»‹ máº·n ngá»t, thÆ°á»ng Äƒn vá»›i cÆ¡m tráº¯ng vÃ  rau luá»™c.",
    ingredients: ["CÃ¡", "NÆ°á»›c máº¯m", "TiÃªu", "CÆ¡m"],
    image: "/images/foods/ca-kho-to.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "canh-chua-ca",
    name: "Canh chua cÃ¡",
    tag: "TrÆ°a / Tá»‘i",
    price: 42000,
    calories: 420,
    time: "18 phÃºt",
    rating: 4.6,
    description: "Canh chua miá»n Nam vá»›i cÃ¡, thÆ¡m, cÃ  chua, báº¡c hÃ  vÃ  rau thÆ¡m.",
    ingredients: ["CÃ¡", "ThÆ¡m", "CÃ  chua", "Báº¡c hÃ "],
    image: "/images/foods/canh-chua-ca.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "chao-ga",
    name: "ChÃ¡o gÃ ",
    tag: "SÃ¡ng / Tá»‘i nháº¹",
    price: 30000,
    calories: 390,
    time: "10 phÃºt",
    rating: 4.5,
    description: "ChÃ¡o má»m, thá»‹t gÃ  xÃ©, hÃ nh, tiÃªu vÃ  rau rÄƒm.",
    ingredients: ["Gáº¡o", "Thá»‹t gÃ ", "HÃ nh", "Rau rÄƒm"],
    image: "/images/foods/chao-ga.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "chao-long",
    name: "ChÃ¡o lÃ²ng",
    tag: "SÃ¡ng / Khuya",
    price: 25000,
    calories: 430,
    time: "10 phÃºt",
    rating: 4.5,
    description: "ChÃ¡o gáº¡o náº¥u nhá»« Äƒn cÃ¹ng lÃ²ng heo, tiáº¿t, gan vÃ  rau thÆ¡m.",
    ingredients: ["Gáº¡o", "LÃ²ng heo", "Tiáº¿t", "Rau thÆ¡m"],
    image: "/images/foods/chao-long.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "chao-suon",
    name: "ChÃ¡o sÆ°á»n",
    tag: "SÃ¡ng / Tá»‘i nháº¹",
    price: 30000,
    calories: 420,
    time: "12 phÃºt",
    rating: 4.5,
    description: "ChÃ¡o gáº¡o náº¥u nhá»« vá»›i sÆ°á»n non má»m ngá»t, hÃ nh lÃ¡ vÃ  tiÃªu â€” áº¥m bá»¥ng vÃ  bá»• dÆ°á»¡ng.",
    ingredients: ["Gáº¡o", "SÆ°á»n non", "HÃ nh lÃ¡", "TiÃªu"],
    image: "/images/foods/chao-suon.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "che-do-den",
    name: "ChÃ¨ Ä‘á»— Ä‘en",
    tag: "Ä‚n nháº¹ / Tá»‘i",
    price: 15000,
    calories: 230,
    time: "5 phÃºt",
    rating: 4.5,
    description: "ChÃ¨ Ä‘á»— Ä‘en náº¥u ngá»t thanh, chan nÆ°á»›c cá»‘t dá»«a bÃ©o thÆ¡m, Äƒn nÃ³ng hay láº¡nh Ä‘á»u ngon.",
    ingredients: ["Äá»— Ä‘en", "ÄÆ°á»ng", "NÆ°á»›c cá»‘t dá»«a", "ÄÃ¡"],
    image: "/images/foods/che-do-den.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "che-thap-cam",
    name: "ChÃ¨ tháº­p cáº©m",
    tag: "Ä‚n nháº¹ / Tá»‘i",
    price: 25000,
    calories: 320,
    time: "5 phÃºt",
    rating: 4.6,
    description: "ChÃ¨ Ä‘á»§ thá»©: tháº¡ch, khoai dáº»o, Ä‘áº­u, háº¡t sen, nÆ°á»›c cá»‘t dá»«a vÃ  Ä‘Ã¡ bÃ o â€” ngá»t mÃ¡t Ä‘Ãºng Ä‘iá»‡u.",
    ingredients: ["Tháº¡ch", "Khoai", "Äáº­u cÃ¡c loáº¡i", "NÆ°á»›c cá»‘t dá»«a"],
    image: "/images/foods/che-thap-cam.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-binh-dan",
    name: "CÆ¡m bÃ¬nh dÃ¢n",
    tag: "TrÆ°a / Tá»‘i",
    price: 35000,
    calories: 700,
    time: "8 phÃºt",
    rating: 4.5,
    description: "CÆ¡m tráº¯ng Äƒn vá»›i mÃ³n máº·n, rau xÃ o hoáº·c luá»™c vÃ  canh.",
    ingredients: ["CÆ¡m", "MÃ³n máº·n", "Rau", "Canh"],
    image: "/images/foods/com-binh-dan.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-dao-ga-chien",
    name: "CÆ¡m Ä‘áº£o gÃ  chiÃªn",
    tag: "TrÆ°a / Tá»‘i",
    price: 40000,
    calories: 650,
    time: "12 phÃºt",
    rating: 4.5,
    description: "CÆ¡m chiÃªn Ä‘áº£o vá»›i gÃ  giÃ²n, trá»©ng, rau cá»§ xÃ o thÆ¡m â€” no bá»¥ng vÃ  tiá»‡n lá»£i.",
    ingredients: ["CÆ¡m", "Thá»‹t gÃ  chiÃªn", "Trá»©ng", "Rau cá»§"],
    image: "/images/foods/com-dao-ga-chien.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-ga-xoi-mam",
    name: "CÆ¡m gÃ  xá»‘i máº¯m",
    tag: "TrÆ°a / Tá»‘i",
    price: 50000,
    calories: 720,
    time: "15 phÃºt",
    rating: 4.7,
    description: "CÆ¡m tráº¯ng Äƒn vá»›i gÃ  xá»‘i má»¡ giÃ²n da, chan máº¯m pha chua ngá»t vÃ  rau sá»‘ng.",
    ingredients: ["CÆ¡m", "GÃ  xá»‘i má»¡", "Máº¯m pha", "Rau sá»‘ng"],
    image: "/images/foods/com-ga-xoi-mam.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-rang-dua-bo",
    name: "CÆ¡m rang dÆ°a bÃ²",
    tag: "TrÆ°a / Tá»‘i",
    price: 40000,
    calories: 600,
    time: "12 phÃºt",
    rating: 4.6,
    description: "CÆ¡m rang thÆ¡m vá»›i bÃ² xÃ o dÆ°a cáº£i, hÃ nh tÃ¢y vÃ  gia vá»‹ â€” vá»«a quen vá»«a láº¡ miá»‡ng.",
    ingredients: ["CÆ¡m", "Thá»‹t bÃ²", "DÆ°a cáº£i", "HÃ nh tÃ¢y"],
    image: "/images/foods/com-rang-dua-bo.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-tam",
    name: "CÆ¡m táº¥m sÆ°á»n bÃ¬ cháº£",
    tag: "SÃ¡ng / TrÆ°a / Tá»‘i",
    price: 45000,
    calories: 780,
    time: "18 phÃºt",
    rating: 4.9,
    description: "CÆ¡m táº¥m Äƒn vá»›i sÆ°á»n nÆ°á»›ng, bÃ¬, cháº£ trá»©ng, má»¡ hÃ nh vÃ  nÆ°á»›c máº¯m.",
    ingredients: ["CÆ¡m táº¥m", "SÆ°á»n nÆ°á»›ng", "BÃ¬", "Cháº£ trá»©ng"],
    image: "/images/foods/com-tam.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-tho",
    name: "CÆ¡m thá»‘",
    tag: "TrÆ°a / Tá»‘i",
    price: 55000,
    calories: 750,
    time: "20 phÃºt",
    rating: 4.7,
    description: "CÆ¡m náº¥u trong thá»‘ Ä‘áº¥t, Äƒn kÃ¨m thá»‹t kho, trá»©ng, rau cáº£i â€” kiá»ƒu áº©m thá»±c Hoa truyá»n thá»‘ng.",
    ingredients: ["CÆ¡m thá»‘", "Thá»‹t kho", "Trá»©ng", "Rau cáº£i"],
    image: "/images/foods/com-tho.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-van-phong",
    name: "CÆ¡m vÄƒn phÃ²ng",
    tag: "TrÆ°a",
    price: 35000,
    calories: 680,
    time: "10 phÃºt",
    rating: 4.4,
    description: "Suáº¥t cÆ¡m trÆ°a tiá»‡n lá»£i cho ngÆ°á»i Ä‘i lÃ m, thÆ°á»ng cÃ³ cÆ¡m, thá»‹t, rau vÃ  canh.",
    ingredients: ["CÆ¡m", "Thá»‹t", "Rau", "Canh"],
    image: "/images/foods/com-van-phong.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "ga-kho-gung",
    name: "GÃ  kho gá»«ng",
    tag: "TrÆ°a / Tá»‘i",
    price: 38000,
    calories: 570,
    time: "18 phÃºt",
    rating: 4.5,
    description: "Thá»‹t gÃ  kho thÆ¡m vá»‹ gá»«ng, máº·n ngá»t vá»«a Äƒn, há»£p vá»›i cÆ¡m nÃ³ng.",
    ingredients: ["Thá»‹t gÃ ", "Gá»«ng", "NÆ°á»›c máº¯m", "CÆ¡m"],
    image: "/images/foods/ga-kho-gung.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "goi-cuon",
    name: "Gá»i cuá»‘n tÃ´m thá»‹t",
    tag: "TrÆ°a / Ä‚n nháº¹",
    price: 25000,
    calories: 260,
    time: "9 phÃºt",
    rating: 4.6,
    description: "Cuá»‘n tÆ°Æ¡i mÃ¡t vá»›i tÃ´m, thá»‹t, bÃºn, rau sá»‘ng vÃ  tÆ°Æ¡ng Ä‘áº­u phá»™ng.",
    ingredients: ["BÃ¡nh trÃ¡ng", "TÃ´m", "Thá»‹t heo", "Rau sá»‘ng"],
    image: "/images/foods/goi-cuon.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "hamburger",
    name: "Hamburger",
    tag: "TrÆ°a / Tá»‘i / Ä‚n nháº¹",
    price: 40000,
    calories: 580,
    time: "10 phÃºt",
    rating: 4.5,
    description: "Burger bÃ² nÆ°á»›ng juicy káº¹p phÃ´ mai, rau xÃ  lÃ¡ch, cÃ  chua vÃ  sá»‘t Ä‘áº·c biá»‡t â€” hÆ°Æ¡ng vá»‹ Má»¹ chuáº©n vá»‹.",
    ingredients: ["BÃ¡nh burger", "Thá»‹t bÃ²", "PhÃ´ mai", "Rau xÃ  lÃ¡ch"],
    image: "/images/foods/hamburger.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "hu-tieu",
    name: "Há»§ tiáº¿u",
    tag: "SÃ¡ng / TrÆ°a / Tá»‘i",
    price: 35000,
    calories: 540,
    time: "12 phÃºt",
    rating: 4.7,
    description: "MÃ³n miá»n Nam vá»›i sá»£i há»§ tiáº¿u, nÆ°á»›c dÃ¹ng xÆ°Æ¡ng, thá»‹t heo, tÃ´m hoáº·c bÃ² viÃªn.",
    ingredients: ["Há»§ tiáº¿u", "Thá»‹t heo", "TÃ´m", "NÆ°á»›c dÃ¹ng"],
    image: "/images/foods/hu-tieu.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "khoai-tay-lac-pho-mai",
    name: "Khoai tÃ¢y láº¯c phÃ´ mai",
    tag: "Ä‚n nháº¹ / Khuya",
    price: 30000,
    calories: 380,
    time: "5 phÃºt",
    rating: 4.6,
    description: "Khoai tÃ¢y chiÃªn giÃ²n láº¯c bá»™t phÃ´ mai thÆ¡m bÃ©o â€” Äƒn váº·t nghiá»‡n khÃ´ng thá»ƒ dá»«ng.",
    ingredients: ["Khoai tÃ¢y", "Bá»™t phÃ´ mai", "Dáº§u Äƒn", "Gia vá»‹"],
    image: "/images/foods/khoai-tay-lac-pho-mai.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "kimbap",
    name: "Kimbap",
    tag: "TrÆ°a / Ä‚n nháº¹",
    price: 15000,
    calories: 310,
    time: "8 phÃºt",
    rating: 4.5,
    description: "CÆ¡m cuá»™n rong biá»ƒn kiá»ƒu HÃ n nhÃ¢n trá»©ng, cÃ  rá»‘t, dÆ°a leo, xÃºc xÃ­ch vÃ  rau bina.",
    ingredients: ["CÆ¡m", "Rong biá»ƒn", "Trá»©ng", "CÃ  rá»‘t"],
    image: "/images/foods/kimbap.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "lau-thai",
    name: "Láº©u ThÃ¡i",
    tag: "Tá»‘i / Cuá»‘i tuáº§n",
    price: 150000,
    calories: 900,
    time: "25 phÃºt",
    rating: 4.7,
    description: "Láº©u chua cay Äƒn chung vá»›i háº£i sáº£n, thá»‹t, náº¥m, rau vÃ  bÃºn hoáº·c mÃ¬.",
    ingredients: ["NÆ°á»›c láº©u", "Háº£i sáº£n", "Rau", "Náº¥m"],
    image: "/images/foods/lau-thai.jpg",
    fallbackImage: fallbackImages.hotpot,
  },
  {
    id: "mien-ga",
    name: "Miáº¿n gÃ ",
    tag: "SÃ¡ng / TrÆ°a / Tá»‘i",
    price: 35000,
    calories: 430,
    time: "10 phÃºt",
    rating: 4.5,
    description: "Miáº¿n dong náº¥u nÆ°á»›c dÃ¹ng gÃ , thá»‹t gÃ  xÃ©, mÄƒng hoáº·c náº¥m.",
    ingredients: ["Miáº¿n", "Thá»‹t gÃ ", "MÄƒng", "HÃ nh"],
    image: "/images/foods/mien-ga.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "mien-ngan-tron",
    name: "Miáº¿n ngan trá»™n",
    tag: "TrÆ°a / Tá»‘i",
    price: 40000,
    calories: 510,
    time: "12 phÃºt",
    rating: 4.7,
    description: "Miáº¿n trá»™n khÃ´ vá»›i thá»‹t ngan xÃ©, hÃ nh phi giÃ²n, láº¡c rang, rau thÆ¡m vÃ  nÆ°á»›c cháº¥m Ä‘áº­m Ä‘Ã .",
    ingredients: ["Miáº¿n", "Thá»‹t ngan", "HÃ nh phi", "Láº¡c rang"],
    image: "/images/foods/mien-ngan-tron.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "mien-xao-hai-san",
    name: "Miáº¿n xÃ o háº£i sáº£n",
    tag: "TrÆ°a / Tá»‘i",
    price: 60000,
    calories: 560,
    time: "15 phÃºt",
    rating: 4.7,
    description: "Miáº¿n xÃ o khÃ´ vá»›i tÃ´m, má»±c, trá»©ng, giÃ¡ Ä‘á»— vÃ  hÃ nh lÃ¡ â€” Ä‘áº­m vá»‹, giÃ²n thÆ¡m.",
    ingredients: ["Miáº¿n", "TÃ´m", "Má»±c", "GiÃ¡ Ä‘á»—"],
    image: "/images/foods/mien-xao-hai-san.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "mi-an-lien",
    name: "MÃ¬ Äƒn liá»n",
    tag: "SÃ¡ng / Ä‚n nháº¹ / Khuya",
    price: 5000,
    calories: 330,
    time: "3 phÃºt",
    rating: 4.0,
    description: "MÃ¬ tÃ´m náº¥u nhanh quen thuá»™c má»i nhÃ  â€” thÃªm trá»©ng hoáº·c rau cho Ä‘á»§ cháº¥t.",
    ingredients: ["MÃ¬ Äƒn liá»n", "GÃ³i gia vá»‹", "Trá»©ng", "HÃ nh lÃ¡"],
    image: "/images/foods/my-tom.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "my-cay-7-cap-do",
    name: "Má»³ cay 7 cáº¥p Ä‘á»™",
    tag: "TrÆ°a / Tá»‘i / Khuya",
    price: 40000,
    calories: 650,
    time: "15 phÃºt",
    rating: 4.6,
    description: "Má»³ cay ná»“ng chá»n cáº¥p Ä‘á»™ 1-7, thÃªm háº£i sáº£n, náº¥m kim chÃ¢m vÃ  rau â€” thá»­ thÃ¡ch kháº©u vá»‹.",
    ingredients: ["Má»³", "Háº£i sáº£n", "Náº¥m kim chÃ¢m", "Sa táº¿ cay"],
    image: "/images/foods/my-cay-7-cap-do.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "my-ga-tan",
    name: "Má»³ gÃ  táº§n",
    tag: "SÃ¡ng / TrÆ°a / Tá»‘i",
    price: 60000,
    calories: 680,
    time: "20 phÃºt",
    rating: 4.7,
    description: "Má»³ náº¥u cÃ¹ng gÃ  táº§n thuá»‘c báº¯c, rau muá»‘ng, trá»©ng vÃ  nÆ°á»›c dÃ¹ng Ä‘áº­m vá»‹ â€” no cÄƒng vÃ  bá»• dÆ°á»¡ng.",
    ingredients: ["Má»³", "GÃ  táº§n", "Rau muá»‘ng", "Trá»©ng"],
    image: "/images/foods/my-ga-tan.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "mi-quang",
    name: "MÃ¬ Quáº£ng",
    tag: "SÃ¡ng / TrÆ°a",
    price: 35000,
    calories: 590,
    time: "12 phÃºt",
    rating: 4.7,
    description: "MÃ¬ vÃ ng miá»n Trung vá»›i nÆ°á»›c dÃ¹ng Ã­t, tÃ´m thá»‹t, trá»©ng cÃºt, Ä‘áº­u phá»™ng.",
    ingredients: ["MÃ¬ Quáº£ng", "TÃ´m", "Thá»‹t", "Äáº­u phá»™ng"],
    image: "/images/foods/mi-quang.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "mi-tron-indo",
    name: "MÃ¬ trá»™n indo",
    tag: "TrÆ°a / Tá»‘i / Ä‚n nháº¹",
    price: 35000,
    calories: 520,
    time: "10 phÃºt",
    rating: 4.5,
    description: "MÃ¬ Indo xÃ o khÃ´ trá»™n sá»‘t Ä‘áº­m Ä‘Ã , thÃªm viÃªn tháº£, xÃºc xÃ­ch, tÃ´m vÃ  báº¯p â€” mÃ³n vá»‰a hÃ¨ hot.",
    ingredients: ["MÃ¬ Indo", "ViÃªn tháº£", "XÃºc xÃ­ch", "Sá»‘t Ä‘áº·c biá»‡t"],
    image: "/images/foods/my-tron-indo.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "my-xao-bo",
    name: "Má»³ xÃ o bÃ²",
    tag: "TrÆ°a / Tá»‘i",
    price: 40000,
    calories: 620,
    time: "15 phÃºt",
    rating: 4.6,
    description: "Má»³ xÃ o khÃ´ vá»›i bÃ² tÃ¡i, cáº£i xanh, giÃ¡ Ä‘á»— vÃ  sá»‘t dáº§u hÃ o â€” no bá»¥ng, Ä‘áº­m vá»‹.",
    ingredients: ["Má»³", "Thá»‹t bÃ²", "Cáº£i xanh", "GiÃ¡ Ä‘á»—"],
    image: "/images/foods/my-xao-bo.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "my-y",
    name: "Má»³ Ã",
    tag: "TrÆ°a / Tá»‘i",
    price: 50000,
    calories: 680,
    time: "20 phÃºt",
    rating: 4.6,
    description: "Spaghetti sá»‘t bolognese thá»‹t bÃ² bÄƒm, cÃ  chua, phÃ´ mai vÃ  rau thÆ¡m â€” hÆ°Æ¡ng vá»‹ Ã giá»¯a lÃ²ng HÃ  Ná»™i.",
    ingredients: ["Spaghetti", "Thá»‹t bÃ² bÄƒm", "Sá»‘t cÃ  chua", "PhÃ´ mai"],
    image: "/images/foods/my-y.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "nem-chua-ran",
    name: "Nem chua rÃ¡n",
    tag: "Ä‚n nháº¹ / Khuya",
    price: 5000,
    calories: 150,
    time: "2 phÃºt",
    rating: 4.3,
    description: "Nem chua bá»c vá» chiÃªn giÃ²n rá»¥m, cháº¥m tÆ°Æ¡ng á»›t cay â€” Äƒn váº·t cá»•ng trÆ°á»ng khÃ´ng thá»ƒ bá» qua.",
    ingredients: ["Nem chua", "Bá»™t chiÃªn xÃ¹", "TÆ°Æ¡ng á»›t"],
    image: "/images/foods/nem-chua-ran.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "nem-lui",
    name: "Nem lá»¥i",
    tag: "TrÆ°a / Tá»‘i",
    price: 35000,
    calories: 520,
    time: "15 phÃºt",
    rating: 4.7,
    description: "Nem thá»‹t heo xiÃªn sáº£ nÆ°á»›ng thÆ¡m, cuá»‘n bÃ¡nh trÃ¡ng vá»›i bÃºn, rau sá»‘ng vÃ  nÆ°á»›c cháº¥m máº¯m nÃªm.",
    ingredients: ["Thá»‹t heo", "Sáº£", "BÃ¡nh trÃ¡ng", "Rau sá»‘ng"],
    image: "/images/foods/nem-lui.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "nem-nuong-nha-trang",
    name: "Nem nÆ°á»›ng Nha Trang",
    tag: "TrÆ°a / Tá»‘i",
    price: 35000,
    calories: 550,
    time: "15 phÃºt",
    rating: 4.8,
    description: "Nem nÆ°á»›ng Ä‘áº·c sáº£n Nha Trang, cuá»‘n bÃ¡nh trÃ¡ng vá»›i bÃºn, rau thÆ¡m, xoÃ i xanh vÃ  tÆ°Æ¡ng Ä‘áº­u phá»™ng.",
    ingredients: ["Nem nÆ°á»›ng", "BÃ¡nh trÃ¡ng", "BÃºn", "TÆ°Æ¡ng Ä‘áº­u phá»™ng"],
    image: "/images/foods/nem-nuong-nha-trang.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "pho-bo",
    name: "Phá»Ÿ bÃ²",
    tag: "SÃ¡ng / TrÆ°a / Tá»‘i",
    price: 35000,
    calories: 520,
    time: "12 phÃºt",
    rating: 4.9,
    description: "MÃ³n nÆ°á»›c phá»• biáº¿n vá»›i bÃ¡nh phá»Ÿ, nÆ°á»›c dÃ¹ng bÃ², thá»‹t bÃ² vÃ  rau thÆ¡m.",
    ingredients: ["BÃ¡nh phá»Ÿ", "Thá»‹t bÃ²", "HÃ nh lÃ¡", "Rau thÆ¡m"],
    image: "/images/foods/pho-bo.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "pho-cuon",
    name: "Phá»Ÿ cuá»‘n",
    tag: "TrÆ°a / Tá»‘i / Ä‚n nháº¹",
    price: 35000,
    calories: 380,
    time: "10 phÃºt",
    rating: 4.5,
    description: "BÃ¡nh phá»Ÿ tÆ°Æ¡i cuá»‘n thá»‹t bÃ² tÃ¡i, rau thÆ¡m, cháº¥m nÆ°á»›c máº¯m gá»«ng hoáº·c tÆ°Æ¡ng hoisin.",
    ingredients: ["BÃ¡nh phá»Ÿ", "Thá»‹t bÃ²", "Rau thÆ¡m", "NÆ°á»›c cháº¥m"],
    image: "/images/foods/pho-cuon.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "pho-ga",
    name: "Phá»Ÿ gÃ ",
    tag: "SÃ¡ng / TrÆ°a",
    price: 35000,
    calories: 480,
    time: "12 phÃºt",
    rating: 4.8,
    description: "Phá»Ÿ nÆ°á»›c dÃ¹ng gÃ  thanh, thá»‹t gÃ  xÃ© hoáº·c cháº·t miáº¿ng, Äƒn cÃ¹ng rau thÆ¡m.",
    ingredients: ["BÃ¡nh phá»Ÿ", "Thá»‹t gÃ ", "HÃ nh", "LÃ¡ chanh"],
    image: "/images/foods/pho-ga.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "pho-tron-ga",
    name: "Phá»Ÿ trá»™n gÃ ",
    tag: "SÃ¡ng / TrÆ°a",
    price: 35000,
    calories: 470,
    time: "10 phÃºt",
    rating: 4.5,
    description: "BÃ¡nh phá»Ÿ trá»™n khÃ´ vá»›i thá»‹t gÃ  xÃ©, hÃ nh phi, láº¡c rang, rau thÆ¡m vÃ  sá»‘t chua ngá»t.",
    ingredients: ["BÃ¡nh phá»Ÿ", "Thá»‹t gÃ ", "HÃ nh phi", "Láº¡c rang"],
    image: "/images/foods/pho-tron-ga.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "pho-xao",
    name: "Phá»Ÿ xÃ o",
    tag: "TrÆ°a / Tá»‘i",
    price: 45000,
    calories: 620,
    time: "15 phÃºt",
    rating: 4.6,
    description: "BÃ¡nh phá»Ÿ xÃ o vá»›i thá»‹t bÃ² hoáº·c gÃ , rau cáº£i, hÃ nh tÃ¢y, sá»‘t dáº§u hÃ o Ä‘áº­m Ä‘Ã .",
    ingredients: ["BÃ¡nh phá»Ÿ", "Thá»‹t bÃ²", "Rau cáº£i", "HÃ nh tÃ¢y"],
    image: "/images/foods/pho-xao.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "pizza",
    name: "Pizza",
    tag: "TrÆ°a / Tá»‘i / Cuá»‘i tuáº§n",
    price: 85000,
    calories: 750,
    time: "20 phÃºt",
    rating: 4.6,
    description: "Pizza Ä‘áº¿ giÃ²n sá»‘t cÃ  chua, phÃ´ mai kÃ©o sá»£i vÃ  topping thá»‹t bÃ² bÄƒm thÆ¡m lá»«ng â€” ngon khÃ´ng kÃ©m hÃ ng Ã.",
    ingredients: ["Äáº¿ pizza", "Sá»‘t cÃ  chua", "PhÃ´ mai", "Thá»‹t bÃ² bÄƒm"],
    image: "/images/foods/pizza.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "rau-muong-xao-toi",
    name: "Rau muá»‘ng xÃ o tá»i",
    tag: "TrÆ°a / Tá»‘i",
    price: 25000,
    calories: 180,
    time: "8 phÃºt",
    rating: 4.4,
    description: "Rau muá»‘ng xÃ o nhanh vá»›i tá»i, mÃ³n rau quen thuá»™c trong bá»¯a cÆ¡m gia Ä‘Ã¬nh.",
    ingredients: ["Rau muá»‘ng", "Tá»i", "Dáº§u Äƒn", "Gia vá»‹"],
    image: "/images/foods/rau-muong-xao-toi.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "tao-pho",
    name: "TÃ o phá»›",
    tag: "Ä‚n nháº¹ / Tá»‘i",
    price: 15000,
    calories: 160,
    time: "2 phÃºt",
    rating: 4.5,
    description: "TÃ o phá»› má»‹n mÃ¡t chan nÆ°á»›c Ä‘Æ°á»ng gá»«ng thÆ¡m â€” mÃ³n Äƒn váº·t HÃ  Ná»™i giáº£n dá»‹ mÃ  khÃ³ quÃªn.",
    ingredients: ["Äáº­u nÃ nh", "NÆ°á»›c Ä‘Æ°á»ng", "Gá»«ng", "ÄÃ¡"],
    image: "/images/foods/tao-pho.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "thit-kho-trung",
    name: "Thá»‹t kho trá»©ng",
    tag: "TrÆ°a / Tá»‘i",
    price: 38000,
    calories: 700,
    time: "20 phÃºt",
    rating: 4.7,
    description: "Thá»‹t ba chá»‰ kho má»m vá»›i trá»©ng, nÆ°á»›c dá»«a hoáº·c nÆ°á»›c mÃ u, Äƒn cÃ¹ng cÆ¡m.",
    ingredients: ["Thá»‹t ba chá»‰", "Trá»©ng", "NÆ°á»›c máº¯m", "CÆ¡m"],
    image: "/images/foods/thit-kho-trung.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "trung-vit-lon",
    name: "Trá»©ng vá»‹t lá»™n",
    tag: "SÃ¡ng / Ä‚n nháº¹ / Khuya",
    price: 8000,
    calories: 180,
    time: "2 phÃºt",
    rating: 4.5,
    description: "Trá»©ng vá»‹t lá»™n luá»™c chÃ­n, Äƒn vá»›i rau rÄƒm, muá»‘i tiÃªu chanh â€” mÃ³n Äƒn váº·t Ä‘Æ°á»ng phá»‘ Ä‘áº·c trÆ°ng.",
    ingredients: ["Trá»©ng vá»‹t lá»™n", "Rau rÄƒm", "Muá»‘i tiÃªu", "Chanh"],
    image: "/images/foods/trung-vit-lon.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "vit-quay",
    name: "Vá»‹t quay",
    tag: "TrÆ°a / Tá»‘i",
    price: 200000,
    calories: 850,
    time: "15 phÃºt",
    rating: 4.5,
    description: "Vá»‹t quay da giÃ²n, thá»‹t má»m, Äƒn vá»›i cÆ¡m, bÃ¡nh mÃ¬ hoáº·c bÃºn. GiÃ¡ 200.000Ä‘/con.",
    ingredients: ["Vá»‹t", "Gia vá»‹ quay", "DÆ°a leo", "NÆ°á»›c cháº¥m"],
    image: "/images/foods/vit-quay.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "xien-ban",
    name: "XiÃªn báº©n",
    tag: "TrÆ°a / Tá»‘i / Ä‚n nháº¹",
    price: 80000,
    calories: 700,
    time: "15 phÃºt",
    rating: 4.6,
    description: "ViÃªn cÃ¡c loáº¡i, Ä‘áº­u phá»¥, xÃºc xÃ­ch xiÃªn que ngÃ¢m sá»‘t cay Ä‘áº·c trÆ°ng â€” mÃ³n Äƒn váº·t hot trend.",
    ingredients: ["ViÃªn cÃ¡c loáº¡i", "Äáº­u phá»¥", "XÃºc xÃ­ch", "Sá»‘t cay"],
    image: "/images/foods/xien-ban.jpg",
    fallbackImage: fallbackImages.hotpot,
  },
  {
    id: "xoi-com",
    name: "XÃ´i cá»‘m",
    tag: "SÃ¡ng / Ä‚n nháº¹",
    price: 20000,
    calories: 380,
    time: "5 phÃºt",
    rating: 4.6,
    description: "XÃ´i cá»‘m xanh mÆ°á»›t, dáº»o thÆ¡m mÃ¹i lÃ¡ dá»©a, Äƒn kÃ¨m dá»«a bÃ o vÃ  Ä‘Æ°á»ng.",
    ingredients: ["Cá»‘m", "Gáº¡o náº¿p", "Dá»«a bÃ o", "ÄÆ°á»ng"],
    image: "/images/foods/xoi-com.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "xoi-ga",
    name: "XÃ´i gÃ ",
    tag: "SÃ¡ng / TrÆ°a",
    price: 30000,
    calories: 650,
    time: "7 phÃºt",
    rating: 4.7,
    description: "XÃ´i náº¿p Äƒn cÃ¹ng thá»‹t gÃ  xÃ©, hÃ nh phi, rau rÄƒm vÃ  nÆ°á»›c sá»‘t.",
    ingredients: ["Gáº¡o náº¿p", "Thá»‹t gÃ ", "HÃ nh phi", "Rau rÄƒm"],
    image: "/images/foods/xoi-ga.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "xoi-lac",
    name: "XÃ´i láº¡c",
    tag: "SÃ¡ng",
    price: 15000,
    calories: 530,
    time: "5 phÃºt",
    rating: 4.4,
    description: "XÃ´i náº¿p trá»™n láº¡c rang, vá»«a dáº»o vá»«a bÃ¹i, Äƒn kÃ¨m muá»‘i vá»«ng hoáº·c ruá»‘c.",
    ingredients: ["Gáº¡o náº¿p", "Láº¡c", "Muá»‘i vá»«ng"],
    image: "/images/foods/xoi-lac.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "xoi-tom",
    name: "XÃ´i tÃ´m",
    tag: "SÃ¡ng / TrÆ°a",
    price: 40000,
    calories: 620,
    time: "8 phÃºt",
    rating: 4.7,
    description: "XÃ´i náº¿p dáº»o Äƒn cÃ¹ng tÃ´m khÃ´, hÃ nh phi giÃ²n, ruá»‘c vÃ  nÆ°á»›c máº¯m pha.",
    ingredients: ["Gáº¡o náº¿p", "TÃ´m khÃ´", "HÃ nh phi", "Ruá»‘c"],
    image: "/images/foods/xoi-tom.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "xoi-xeo",
    name: "XÃ´i xÃ©o",
    tag: "SÃ¡ng",
    price: 15000,
    calories: 520,
    time: "5 phÃºt",
    rating: 4.6,
    description: "XÃ´i náº¿p dáº»o Äƒn vá»›i Ä‘áº­u xanh, hÃ nh phi vÃ  má»¡ hÃ nh.",
    ingredients: ["Gáº¡o náº¿p", "Äáº­u xanh", "HÃ nh phi", "Má»¡ hÃ nh"],
    image: "/images/foods/xoi-xeo.jpg",
    fallbackImage: fallbackImages.rice,
  },
];

