const fallbackImages = {
  noodle:
    "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=1200&q=80",
  rice:
    "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=1200&q=80",
  bread:
    "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=1200&q=80",
  roll:
    "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
  hotpot:
    "https://images.unsplash.com/photo-1617196034183-421b4917c92d?auto=format&fit=crop&w=1200&q=80",
};

export const foods = [
  {
    id: "banh-bao",
    name: "Bánh bao",
    tag: "Sáng / Ăn nhẹ",
    price: 15000,
    calories: 320,
    time: "5 phút",
    rating: 4.4,
    description: "Bánh hấp nhân thịt, trứng cút, miến và mộc nhĩ.",
    ingredients: ["Bột mì", "Thịt băm", "Trứng cút", "Mộc nhĩ"],
    image: "/images/foods/banh-bao.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-canh",
    name: "Bánh canh",
    tag: "Sáng / Trưa / Tối",
    price: 32000,
    calories: 540,
    time: "12 phút",
    rating: 4.6,
    description: "Sợi bánh canh dai mềm, nước dùng sánh, thường ăn với cua, chả cá hoặc giò heo.",
    ingredients: ["Bánh canh", "Nước dùng", "Chả cá", "Giò heo"],
    image: "/images/foods/banh-canh.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "banh-chuoi-ngo-khoai",
    name: "Bánh chuối / ngô / khoai",
    tag: "Sáng / Ăn nhẹ",
    price: 10000,
    calories: 200,
    time: "2 phút",
    rating: 4.3,
    description: "Bánh nướng hoặc hấp từ chuối, ngô hoặc khoai — dân dã, thơm ngọt tự nhiên.",
    ingredients: ["Chuối / Ngô / Khoai", "Bột nếp", "Đường", "Dừa"],
    image: "/images/foods/banh-chuoi-ngo-khoai.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-cuon",
    name: "Bánh cuốn",
    tag: "Sáng",
    price: 30000,
    calories: 360,
    time: "8 phút",
    rating: 4.6,
    description: "Bánh bột gạo tráng mỏng cuốn nhân thịt băm, mộc nhĩ, ăn với nước mắm.",
    ingredients: ["Bột gạo", "Thịt băm", "Mộc nhĩ", "Nước mắm"],
    image: "/images/foods/banh-cuon.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-gio-mat-mia",
    name: "Bánh gio mật mía",
    tag: "Sáng / Ăn nhẹ",
    price: 10000,
    calories: 190,
    time: "3 phút",
    rating: 4.4,
    description: "Bánh gio trong mịn, vị thanh nhẹ, ăn với mật mía ngọt thơm — món truyền thống giản dị.",
    ingredients: ["Bột gạo nếp tro", "Mật mía", "Lá chuối"],
    image: "/images/foods/banh-gio-mat-mia.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-gio",
    name: "Bánh giò",
    tag: "Sáng / Ăn nhẹ",
    price: 15000,
    calories: 310,
    time: "5 phút",
    rating: 4.5,
    description: "Bánh bột gạo hấp lá chuối, nhân thịt băm, mộc nhĩ, ăn kèm chả lụa và tương ớt.",
    ingredients: ["Bột gạo", "Thịt băm", "Mộc nhĩ", "Chả lụa"],
    image: "/images/foods/banh-gio.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-goi",
    name: "Bánh gối",
    tag: "Sáng / Ăn nhẹ",
    price: 8000,
    calories: 220,
    time: "3 phút",
    rating: 4.4,
    description: "Bánh chiên giòn nhân thịt, mộc nhĩ, miến và trứng cút — ăn vặt cổng trường quen thuộc.",
    ingredients: ["Bột mì", "Thịt băm", "Mộc nhĩ", "Miến"],
    image: "/images/foods/banh-goi.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-khuc",
    name: "Bánh khúc",
    tag: "Sáng / Ăn nhẹ",
    price: 15000,
    calories: 420,
    time: "5 phút",
    rating: 4.5,
    description: "Xôi gói bên ngoài, nhân đậu xanh và thịt mỡ, áo lớp nếp dẻo thơm mùi rau khúc.",
    ingredients: ["Gạo nếp", "Rau khúc", "Đậu xanh", "Thịt mỡ"],
    image: "/images/foods/banh-khuc.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "banh-mi",
    name: "Bánh mì",
    tag: "Sáng / Ăn nhẹ",
    price: 25000,
    calories: 430,
    time: "7 phút",
    rating: 4.8,
    description: "Bánh mì giòn kẹp pate, thịt, trứng hoặc gà, thêm đồ chua và rau thơm.",
    ingredients: ["Bánh mì", "Pate", "Thịt", "Đồ chua"],
    image: "/images/foods/banh-mi.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-my-chao",
    name: "Bánh mỳ chảo",
    tag: "Sáng / Trưa",
    price: 40000,
    calories: 620,
    time: "12 phút",
    rating: 4.7,
    description: "Chảo gang nóng hổi với bò, xúc xích, trứng ốp la, rau và bánh mỳ giòn — bữa sáng sung túc.",
    ingredients: ["Bánh mỳ", "Thịt bò", "Trứng", "Xúc xích"],
    image: "/images/foods/banh-my-chao.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-my-nem-khoai",
    name: "Bánh mỳ nem khoai",
    tag: "Sáng / Ăn nhẹ",
    price: 25000,
    calories: 420,
    time: "5 phút",
    rating: 4.5,
    description: "Bánh mỳ giòn kẹp nem khoai chiên xù, sốt tương ớt và mayonnaise — combo vỉa hè hot hit.",
    ingredients: ["Bánh mỳ", "Nem khoai", "Tương ớt", "Mayonnaise"],
    image: "/images/foods/banh-my-nem-khoai.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-my-tam-giac",
    name: "Bánh mỳ tam giác",
    tag: "Sáng / Ăn nhẹ",
    price: 25000,
    calories: 480,
    time: "5 phút",
    rating: 4.6,
    description: "Bánh mỳ nướng hình tam giác kẹp thịt, rau và sốt — nhanh gọn, đầy đặn cho bữa sáng.",
    ingredients: ["Bánh mỳ", "Thịt", "Rau", "Sốt"],
    image: "/images/foods/banh-my-tam-giac.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-ngot",
    name: "Bánh ngọt",
    tag: "Sáng / Ăn nhẹ",
    price: 18000,
    calories: 280,
    time: "3 phút",
    rating: 4.3,
    description: "Bánh ngọt các loại: su kem, bánh bông lan, croissant... nhẹ nhàng cho bữa sáng hoặc ăn vặt.",
    ingredients: ["Bột mì", "Trứng", "Bơ", "Đường"],
    image: "/images/foods/banh-ngot.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-ran",
    name: "Bánh rán",
    tag: "Sáng / Ăn nhẹ",
    price: 5000,
    calories: 180,
    time: "2 phút",
    rating: 4.2,
    description: "Bánh rán vừng giòn ngoài mềm trong, nhân đậu xanh ngọt bùi, ăn nóng rất ngon.",
    ingredients: ["Bột nếp", "Đậu xanh", "Vừng", "Đường"],
    image: "/images/foods/banh-ran.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "banh-tacos",
    name: "Bánh tacos",
    tag: "Trưa / Tối / Ăn nhẹ",
    price: 25000,
    calories: 420,
    time: "10 phút",
    rating: 4.5,
    description: "Vỏ bánh tacos giòn hoặc mềm nhân gà/bò xào, bắp cải tím, cà rốt và sốt cay ngọt.",
    ingredients: ["Vỏ tacos", "Thịt gà / bò", "Bắp cải tím", "Sốt đặc biệt"],
    image: "/images/foods/banh-tacos.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-te",
    name: "Bánh tẻ",
    tag: "Sáng / Ăn nhẹ",
    price: 6000,
    calories: 220,
    time: "3 phút",
    rating: 4.3,
    description: "Bánh bột gạo tẻ gói lá dong, nhân thịt mộc nhĩ, chấm nước mắm gừng.",
    ingredients: ["Bột gạo tẻ", "Thịt heo", "Mộc nhĩ", "Lá dong"],
    image: "/images/foods/banh-te.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-trang-cuon",
    name: "Bánh tráng cuộn",
    tag: "Trưa / Ăn nhẹ",
    price: 25000,
    calories: 320,
    time: "7 phút",
    rating: 4.6,
    description: "Bánh tráng cuộn xoài xanh, tôm khô, sa tế, tương và các topping chua cay mặn ngọt.",
    ingredients: ["Bánh tráng", "Xoài xanh", "Tôm khô", "Sa tế"],
    image: "/images/foods/banh-trang-cuon.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "banh-xeo",
    name: "Bánh xèo",
    tag: "Trưa / Tối",
    price: 38000,
    calories: 640,
    time: "18 phút",
    rating: 4.6,
    description: "Bánh bột nghệ chiên giòn với tôm, thịt, giá, cuốn rau sống chấm nước mắm.",
    ingredients: ["Bột gạo", "Tôm", "Thịt", "Giá"],
    image: "/images/foods/banh-xeo.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "bun-bo-hue",
    name: "Bún bò Huế",
    tag: "Sáng / Trưa / Tối",
    price: 40000,
    calories: 620,
    time: "15 phút",
    rating: 4.9,
    description: "Bún nước đậm vị miền Trung với bò, giò heo, sả và sa tế.",
    ingredients: ["Bún", "Thịt bò", "Giò heo", "Sả"],
    image: "/images/foods/bun-bo-hue.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-ca",
    name: "Bún cá",
    tag: "Sáng / Trưa",
    price: 35000,
    calories: 470,
    time: "12 phút",
    rating: 4.5,
    description: "Bún nước với cá chiên hoặc cá hấp, cà chua, thì là và rau sống.",
    ingredients: ["Bún", "Cá", "Cà chua", "Thì là"],
    image: "/images/foods/bun-ca.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-cha",
    name: "Bún chả Hà Nội",
    tag: "Trưa / Tối",
    price: 40000,
    calories: 610,
    time: "15 phút",
    rating: 4.8,
    description: "Bún tươi ăn với chả nướng, thịt nướng, nước chấm và rau sống.",
    ingredients: ["Bún", "Chả nướng", "Thịt nướng", "Rau sống"],
    image: "/images/foods/bun-cha.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-dau-mam-tom",
    name: "Bún đậu mắm tôm",
    tag: "Trưa / Tối",
    price: 38000,
    calories: 720,
    time: "12 phút",
    rating: 4.6,
    description: "Bún lá, đậu phụ chiên, thịt luộc, chả cốm, rau thơm và mắm tôm.",
    ingredients: ["Bún", "Đậu phụ", "Thịt luộc", "Mắm tôm"],
    image: "/images/foods/bun-dau-mam-tom.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-moc-suon",
    name: "Bún mọc sườn",
    tag: "Sáng / Trưa / Tối",
    price: 40000,
    calories: 580,
    time: "15 phút",
    rating: 4.7,
    description: "Bún nước ngọt xương, viên mọc thịt, sườn non, chả và hành lá thơm.",
    ingredients: ["Bún", "Viên mọc", "Sườn non", "Chả"],
    image: "/images/foods/bun-moc-suon.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-ngan-nuoc",
    name: "Bún ngan nước",
    tag: "Sáng / Trưa / Tối",
    price: 40000,
    calories: 560,
    time: "15 phút",
    rating: 4.7,
    description: "Bún ngan nước dùng trong ngọt, thịt ngan mềm, chả, rau thơm và hành phi.",
    ingredients: ["Bún", "Thịt ngan", "Chả", "Hành phi"],
    image: "/images/foods/bun-ngan-nuoc.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-oc",
    name: "Bún ốc",
    tag: "Sáng / Trưa",
    price: 35000,
    calories: 460,
    time: "12 phút",
    rating: 4.5,
    description: "Bún nước vị chua thanh với ốc, cà chua, rau thơm và ớt chưng.",
    ingredients: ["Bún", "Ốc", "Cà chua", "Rau thơm"],
    image: "/images/foods/bun-oc.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-rieu",
    name: "Bún riêu cua",
    tag: "Sáng / Trưa",
    price: 35000,
    calories: 500,
    time: "12 phút",
    rating: 4.7,
    description: "Bún nước vị chua nhẹ, riêu cua, cà chua, đậu phụ và rau sống.",
    ingredients: ["Bún", "Riêu cua", "Cà chua", "Đậu phụ"],
    image: "/images/foods/bun-rieu.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "bun-thit-nuong",
    name: "Bún thịt nướng",
    tag: "Trưa / Tối",
    price: 35000,
    calories: 590,
    time: "12 phút",
    rating: 4.7,
    description: "Bún khô ăn với thịt nướng, rau, đồ chua, đậu phộng và nước mắm.",
    ingredients: ["Bún", "Thịt nướng", "Rau", "Đậu phộng"],
    image: "/images/foods/bun-thit-nuong.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "ca-kho-to",
    name: "Cá kho tộ",
    tag: "Trưa / Tối",
    price: 45000,
    calories: 560,
    time: "20 phút",
    rating: 4.7,
    description: "Cá kho nước màu đậm, vị mặn ngọt, thường ăn với cơm trắng và rau luộc.",
    ingredients: ["Cá", "Nước mắm", "Tiêu", "Cơm"],
    image: "/images/foods/ca-kho-to.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "canh-chua-ca",
    name: "Canh chua cá",
    tag: "Trưa / Tối",
    price: 42000,
    calories: 420,
    time: "18 phút",
    rating: 4.6,
    description: "Canh chua miền Nam với cá, thơm, cà chua, bạc hà và rau thơm.",
    ingredients: ["Cá", "Thơm", "Cà chua", "Bạc hà"],
    image: "/images/foods/canh-chua-ca.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "chao-ga",
    name: "Cháo gà",
    tag: "Sáng / Tối nhẹ",
    price: 30000,
    calories: 390,
    time: "10 phút",
    rating: 4.5,
    description: "Cháo mềm, thịt gà xé, hành, tiêu và rau răm.",
    ingredients: ["Gạo", "Thịt gà", "Hành", "Rau răm"],
    image: "/images/foods/chao-ga.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "chao-long",
    name: "Cháo lòng",
    tag: "Sáng / Khuya",
    price: 25000,
    calories: 430,
    time: "10 phút",
    rating: 4.5,
    description: "Cháo gạo nấu nhừ ăn cùng lòng heo, tiết, gan và rau thơm.",
    ingredients: ["Gạo", "Lòng heo", "Tiết", "Rau thơm"],
    image: "/images/foods/chao-long.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "chao-suon",
    name: "Cháo sườn",
    tag: "Sáng / Tối nhẹ",
    price: 30000,
    calories: 420,
    time: "12 phút",
    rating: 4.5,
    description: "Cháo gạo nấu nhừ với sườn non mềm ngọt, hành lá và tiêu — ấm bụng và bổ dưỡng.",
    ingredients: ["Gạo", "Sườn non", "Hành lá", "Tiêu"],
    image: "/images/foods/chao-suon.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "che-do-den",
    name: "Chè đỗ đen",
    tag: "Ăn nhẹ / Tối",
    price: 15000,
    calories: 230,
    time: "5 phút",
    rating: 4.5,
    description: "Chè đỗ đen nấu ngọt thanh, chan nước cốt dừa béo thơm, ăn nóng hay lạnh đều ngon.",
    ingredients: ["Đỗ đen", "Đường", "Nước cốt dừa", "Đá"],
    image: "/images/foods/che-do-den.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "che-thap-cam",
    name: "Chè thập cẩm",
    tag: "Ăn nhẹ / Tối",
    price: 25000,
    calories: 320,
    time: "5 phút",
    rating: 4.6,
    description: "Chè đủ thứ: thạch, khoai dẻo, đậu, hạt sen, nước cốt dừa và đá bào — ngọt mát đúng điệu.",
    ingredients: ["Thạch", "Khoai", "Đậu các loại", "Nước cốt dừa"],
    image: "/images/foods/che-thap-cam.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-binh-dan",
    name: "Cơm bình dân",
    tag: "Trưa / Tối",
    price: 35000,
    calories: 700,
    time: "8 phút",
    rating: 4.5,
    description: "Cơm trắng ăn với món mặn, rau xào hoặc luộc và canh.",
    ingredients: ["Cơm", "Món mặn", "Rau", "Canh"],
    image: "/images/foods/com-binh-dan.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-dao-ga-chien",
    name: "Cơm đảo gà chiên",
    tag: "Trưa / Tối",
    price: 40000,
    calories: 650,
    time: "12 phút",
    rating: 4.5,
    description: "Cơm chiên đảo với gà giòn, trứng, rau củ xào thơm — no bụng và tiện lợi.",
    ingredients: ["Cơm", "Thịt gà chiên", "Trứng", "Rau củ"],
    image: "/images/foods/com-dao-ga-chien.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-ga-xoi-mam",
    name: "Cơm gà xối mắm",
    tag: "Trưa / Tối",
    price: 50000,
    calories: 720,
    time: "15 phút",
    rating: 4.7,
    description: "Cơm trắng ăn với gà xối mỡ giòn da, chan mắm pha chua ngọt và rau sống.",
    ingredients: ["Cơm", "Gà xối mỡ", "Mắm pha", "Rau sống"],
    image: "/images/foods/com-ga-xoi-mam.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-rang-dua-bo",
    name: "Cơm rang dưa bò",
    tag: "Trưa / Tối",
    price: 40000,
    calories: 600,
    time: "12 phút",
    rating: 4.6,
    description: "Cơm rang thơm với bò xào dưa cải, hành tây và gia vị — vừa quen vừa lạ miệng.",
    ingredients: ["Cơm", "Thịt bò", "Dưa cải", "Hành tây"],
    image: "/images/foods/com-rang-dua-bo.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-tam",
    name: "Cơm tấm sườn bì chả",
    tag: "Sáng / Trưa / Tối",
    price: 45000,
    calories: 780,
    time: "18 phút",
    rating: 4.9,
    description: "Cơm tấm ăn với sườn nướng, bì, chả trứng, mỡ hành và nước mắm.",
    ingredients: ["Cơm tấm", "Sườn nướng", "Bì", "Chả trứng"],
    image: "/images/foods/com-tam.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-tho",
    name: "Cơm thố",
    tag: "Trưa / Tối",
    price: 55000,
    calories: 750,
    time: "20 phút",
    rating: 4.7,
    description: "Cơm nấu trong thố đất, ăn kèm thịt kho, trứng, rau cải — kiểu ẩm thực Hoa truyền thống.",
    ingredients: ["Cơm thố", "Thịt kho", "Trứng", "Rau cải"],
    image: "/images/foods/com-tho.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "com-van-phong",
    name: "Cơm văn phòng",
    tag: "Trưa",
    price: 35000,
    calories: 680,
    time: "10 phút",
    rating: 4.4,
    description: "Suất cơm trưa tiện lợi cho người đi làm, thường có cơm, thịt, rau và canh.",
    ingredients: ["Cơm", "Thịt", "Rau", "Canh"],
    image: "/images/foods/com-van-phong.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "ga-kho-gung",
    name: "Gà kho gừng",
    tag: "Trưa / Tối",
    price: 38000,
    calories: 570,
    time: "18 phút",
    rating: 4.5,
    description: "Thịt gà kho thơm vị gừng, mặn ngọt vừa ăn, hợp với cơm nóng.",
    ingredients: ["Thịt gà", "Gừng", "Nước mắm", "Cơm"],
    image: "/images/foods/ga-kho-gung.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "goi-cuon",
    name: "Gỏi cuốn tôm thịt",
    tag: "Trưa / Ăn nhẹ",
    price: 25000,
    calories: 260,
    time: "9 phút",
    rating: 4.6,
    description: "Cuốn tươi mát với tôm, thịt, bún, rau sống và tương đậu phộng.",
    ingredients: ["Bánh tráng", "Tôm", "Thịt heo", "Rau sống"],
    image: "/images/foods/goi-cuon.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "hamburger",
    name: "Hamburger",
    tag: "Trưa / Tối / Ăn nhẹ",
    price: 40000,
    calories: 580,
    time: "10 phút",
    rating: 4.5,
    description: "Burger bò nướng juicy kẹp phô mai, rau xà lách, cà chua và sốt đặc biệt — hương vị Mỹ chuẩn vị.",
    ingredients: ["Bánh burger", "Thịt bò", "Phô mai", "Rau xà lách"],
    image: "/images/foods/hamburger.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "hu-tieu",
    name: "Hủ tiếu",
    tag: "Sáng / Trưa / Tối",
    price: 35000,
    calories: 540,
    time: "12 phút",
    rating: 4.7,
    description: "Món miền Nam với sợi hủ tiếu, nước dùng xương, thịt heo, tôm hoặc bò viên.",
    ingredients: ["Hủ tiếu", "Thịt heo", "Tôm", "Nước dùng"],
    image: "/images/foods/hu-tieu.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "khoai-tay-lac-pho-mai",
    name: "Khoai tây lắc phô mai",
    tag: "Ăn nhẹ / Khuya",
    price: 30000,
    calories: 380,
    time: "5 phút",
    rating: 4.6,
    description: "Khoai tây chiên giòn lắc bột phô mai thơm béo — ăn vặt nghiện không thể dừng.",
    ingredients: ["Khoai tây", "Bột phô mai", "Dầu ăn", "Gia vị"],
    image: "/images/foods/khoai-tay-lac-pho-mai.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "kimbap",
    name: "Kimbap",
    tag: "Trưa / Ăn nhẹ",
    price: 15000,
    calories: 310,
    time: "8 phút",
    rating: 4.5,
    description: "Cơm cuộn rong biển kiểu Hàn nhân trứng, cà rốt, dưa leo, xúc xích và rau bina.",
    ingredients: ["Cơm", "Rong biển", "Trứng", "Cà rốt"],
    image: "/images/foods/kimbap.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "lau-thai",
    name: "Lẩu Thái",
    tag: "Tối / Cuối tuần",
    price: 150000,
    calories: 900,
    time: "25 phút",
    rating: 4.7,
    description: "Lẩu chua cay ăn chung với hải sản, thịt, nấm, rau và bún hoặc mì.",
    ingredients: ["Nước lẩu", "Hải sản", "Rau", "Nấm"],
    image: "/images/foods/lau-thai.jpg",
    fallbackImage: fallbackImages.hotpot,
  },
  {
    id: "mien-ga",
    name: "Miến gà",
    tag: "Sáng / Trưa / Tối",
    price: 35000,
    calories: 430,
    time: "10 phút",
    rating: 4.5,
    description: "Miến dong nấu nước dùng gà, thịt gà xé, măng hoặc nấm.",
    ingredients: ["Miến", "Thịt gà", "Măng", "Hành"],
    image: "/images/foods/mien-ga.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "mien-ngan-tron",
    name: "Miến ngan trộn",
    tag: "Trưa / Tối",
    price: 40000,
    calories: 510,
    time: "12 phút",
    rating: 4.7,
    description: "Miến trộn khô với thịt ngan xé, hành phi giòn, lạc rang, rau thơm và nước chấm đậm đà.",
    ingredients: ["Miến", "Thịt ngan", "Hành phi", "Lạc rang"],
    image: "/images/foods/mien-ngan-tron.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "mien-xao-hai-san",
    name: "Miến xào hải sản",
    tag: "Trưa / Tối",
    price: 60000,
    calories: 560,
    time: "15 phút",
    rating: 4.7,
    description: "Miến xào khô với tôm, mực, trứng, giá đỗ và hành lá — đậm vị, giòn thơm.",
    ingredients: ["Miến", "Tôm", "Mực", "Giá đỗ"],
    image: "/images/foods/mien-xao-hai-san.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "mi-an-lien",
    name: "Mì ăn liền",
    tag: "Sáng / Ăn nhẹ / Khuya",
    price: 5000,
    calories: 330,
    time: "3 phút",
    rating: 4.0,
    description: "Mì tôm nấu nhanh quen thuộc mọi nhà — thêm trứng hoặc rau cho đủ chất.",
    ingredients: ["Mì ăn liền", "Gói gia vị", "Trứng", "Hành lá"],
    image: "/images/foods/my-tom.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "my-cay-7-cap-do",
    name: "Mỳ cay 7 cấp độ",
    tag: "Trưa / Tối / Khuya",
    price: 40000,
    calories: 650,
    time: "15 phút",
    rating: 4.6,
    description: "Mỳ cay nồng chọn cấp độ 1-7, thêm hải sản, nấm kim châm và rau — thử thách khẩu vị.",
    ingredients: ["Mỳ", "Hải sản", "Nấm kim châm", "Sa tế cay"],
    image: "/images/foods/my-cay-7-cap-do.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "my-ga-tan",
    name: "Mỳ gà tần",
    tag: "Sáng / Trưa / Tối",
    price: 60000,
    calories: 680,
    time: "20 phút",
    rating: 4.7,
    description: "Mỳ nấu cùng gà tần thuốc bắc, rau muống, trứng và nước dùng đậm vị — no căng và bổ dưỡng.",
    ingredients: ["Mỳ", "Gà tần", "Rau muống", "Trứng"],
    image: "/images/foods/my-ga-tan.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "mi-quang",
    name: "Mì Quảng",
    tag: "Sáng / Trưa",
    price: 35000,
    calories: 590,
    time: "12 phút",
    rating: 4.7,
    description: "Mì vàng miền Trung với nước dùng ít, tôm thịt, trứng cút, đậu phộng.",
    ingredients: ["Mì Quảng", "Tôm", "Thịt", "Đậu phộng"],
    image: "/images/foods/mi-quang.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "mi-tron-indo",
    name: "Mì trộn indo",
    tag: "Trưa / Tối / Ăn nhẹ",
    price: 35000,
    calories: 520,
    time: "10 phút",
    rating: 4.5,
    description: "Mì Indo xào khô trộn sốt đậm đà, thêm viên thả, xúc xích, tôm và bắp — món vỉa hè hot.",
    ingredients: ["Mì Indo", "Viên thả", "Xúc xích", "Sốt đặc biệt"],
    image: "/images/foods/my-tron-indo.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "my-xao-bo",
    name: "Mỳ xào bò",
    tag: "Trưa / Tối",
    price: 40000,
    calories: 620,
    time: "15 phút",
    rating: 4.6,
    description: "Mỳ xào khô với bò tái, cải xanh, giá đỗ và sốt dầu hào — no bụng, đậm vị.",
    ingredients: ["Mỳ", "Thịt bò", "Cải xanh", "Giá đỗ"],
    image: "/images/foods/my-xao-bo.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "my-y",
    name: "Mỳ Ý",
    tag: "Trưa / Tối",
    price: 50000,
    calories: 680,
    time: "20 phút",
    rating: 4.6,
    description: "Spaghetti sốt bolognese thịt bò băm, cà chua, phô mai và rau thơm — hương vị Ý giữa lòng Hà Nội.",
    ingredients: ["Spaghetti", "Thịt bò băm", "Sốt cà chua", "Phô mai"],
    image: "/images/foods/my-y.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "nem-chua-ran",
    name: "Nem chua rán",
    tag: "Ăn nhẹ / Khuya",
    price: 5000,
    calories: 150,
    time: "2 phút",
    rating: 4.3,
    description: "Nem chua bọc vỏ chiên giòn rụm, chấm tương ớt cay — ăn vặt cổng trường không thể bỏ qua.",
    ingredients: ["Nem chua", "Bột chiên xù", "Tương ớt"],
    image: "/images/foods/nem-chua-ran.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "nem-lui",
    name: "Nem lụi",
    tag: "Trưa / Tối",
    price: 35000,
    calories: 520,
    time: "15 phút",
    rating: 4.7,
    description: "Nem thịt heo xiên sả nướng thơm, cuốn bánh tráng với bún, rau sống và nước chấm mắm nêm.",
    ingredients: ["Thịt heo", "Sả", "Bánh tráng", "Rau sống"],
    image: "/images/foods/nem-lui.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "nem-nuong-nha-trang",
    name: "Nem nướng Nha Trang",
    tag: "Trưa / Tối",
    price: 35000,
    calories: 550,
    time: "15 phút",
    rating: 4.8,
    description: "Nem nướng đặc sản Nha Trang, cuốn bánh tráng với bún, rau thơm, xoài xanh và tương đậu phộng.",
    ingredients: ["Nem nướng", "Bánh tráng", "Bún", "Tương đậu phộng"],
    image: "/images/foods/nem-nuong-nha-trang.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "pho-bo",
    name: "Phở bò",
    tag: "Sáng / Trưa / Tối",
    price: 35000,
    calories: 520,
    time: "12 phút",
    rating: 4.9,
    description: "Món nước phổ biến với bánh phở, nước dùng bò, thịt bò và rau thơm.",
    ingredients: ["Bánh phở", "Thịt bò", "Hành lá", "Rau thơm"],
    image: "/images/foods/pho-bo.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "pho-cuon",
    name: "Phở cuốn",
    tag: "Trưa / Tối / Ăn nhẹ",
    price: 35000,
    calories: 380,
    time: "10 phút",
    rating: 4.5,
    description: "Bánh phở tươi cuốn thịt bò tái, rau thơm, chấm nước mắm gừng hoặc tương hoisin.",
    ingredients: ["Bánh phở", "Thịt bò", "Rau thơm", "Nước chấm"],
    image: "/images/foods/pho-cuon.jpg",
    fallbackImage: fallbackImages.roll,
  },
  {
    id: "pho-ga",
    name: "Phở gà",
    tag: "Sáng / Trưa",
    price: 35000,
    calories: 480,
    time: "12 phút",
    rating: 4.8,
    description: "Phở nước dùng gà thanh, thịt gà xé hoặc chặt miếng, ăn cùng rau thơm.",
    ingredients: ["Bánh phở", "Thịt gà", "Hành", "Lá chanh"],
    image: "/images/foods/pho-ga.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "pho-tron-ga",
    name: "Phở trộn gà",
    tag: "Sáng / Trưa",
    price: 35000,
    calories: 470,
    time: "10 phút",
    rating: 4.5,
    description: "Bánh phở trộn khô với thịt gà xé, hành phi, lạc rang, rau thơm và sốt chua ngọt.",
    ingredients: ["Bánh phở", "Thịt gà", "Hành phi", "Lạc rang"],
    image: "/images/foods/pho-tron-ga.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "pho-xao",
    name: "Phở xào",
    tag: "Trưa / Tối",
    price: 45000,
    calories: 620,
    time: "15 phút",
    rating: 4.6,
    description: "Bánh phở xào với thịt bò hoặc gà, rau cải, hành tây, sốt dầu hào đậm đà.",
    ingredients: ["Bánh phở", "Thịt bò", "Rau cải", "Hành tây"],
    image: "/images/foods/pho-xao.jpg",
    fallbackImage: fallbackImages.noodle,
  },
  {
    id: "pizza",
    name: "Pizza",
    tag: "Trưa / Tối / Cuối tuần",
    price: 85000,
    calories: 750,
    time: "20 phút",
    rating: 4.6,
    description: "Pizza đế giòn sốt cà chua, phô mai kéo sợi và topping thịt bò băm thơm lừng — ngon không kém hàng Ý.",
    ingredients: ["Đế pizza", "Sốt cà chua", "Phô mai", "Thịt bò băm"],
    image: "/images/foods/pizza.jpg",
    fallbackImage: fallbackImages.bread,
  },
  {
    id: "rau-muong-xao-toi",
    name: "Rau muống xào tỏi",
    tag: "Trưa / Tối",
    price: 25000,
    calories: 180,
    time: "8 phút",
    rating: 4.4,
    description: "Rau muống xào nhanh với tỏi, món rau quen thuộc trong bữa cơm gia đình.",
    ingredients: ["Rau muống", "Tỏi", "Dầu ăn", "Gia vị"],
    image: "/images/foods/rau-muong-xao-toi.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "tao-pho",
    name: "Tào phớ",
    tag: "Ăn nhẹ / Tối",
    price: 15000,
    calories: 160,
    time: "2 phút",
    rating: 4.5,
    description: "Tào phớ mịn mát chan nước đường gừng thơm — món ăn vặt Hà Nội giản dị mà khó quên.",
    ingredients: ["Đậu nành", "Nước đường", "Gừng", "Đá"],
    image: "/images/foods/tao-pho.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "thit-kho-trung",
    name: "Thịt kho trứng",
    tag: "Trưa / Tối",
    price: 38000,
    calories: 700,
    time: "20 phút",
    rating: 4.7,
    description: "Thịt ba chỉ kho mềm với trứng, nước dừa hoặc nước màu, ăn cùng cơm.",
    ingredients: ["Thịt ba chỉ", "Trứng", "Nước mắm", "Cơm"],
    image: "/images/foods/thit-kho-trung.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "trung-vit-lon",
    name: "Trứng vịt lộn",
    tag: "Sáng / Ăn nhẹ / Khuya",
    price: 8000,
    calories: 180,
    time: "2 phút",
    rating: 4.5,
    description: "Trứng vịt lộn luộc chín, ăn với rau răm, muối tiêu chanh — món ăn vặt đường phố đặc trưng.",
    ingredients: ["Trứng vịt lộn", "Rau răm", "Muối tiêu", "Chanh"],
    image: "/images/foods/trung-vit-lon.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "vit-quay",
    name: "Vịt quay",
    tag: "Trưa / Tối",
    price: 200000,
    calories: 850,
    time: "15 phút",
    rating: 4.5,
    description: "Vịt quay da giòn, thịt mềm, ăn với cơm, bánh mì hoặc bún. Giá 200.000đ/con.",
    ingredients: ["Vịt", "Gia vị quay", "Dưa leo", "Nước chấm"],
    image: "/images/foods/vit-quay.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "xien-ban",
    name: "Xiên bẩn",
    tag: "Trưa / Tối / Ăn nhẹ",
    price: 80000,
    calories: 700,
    time: "15 phút",
    rating: 4.6,
    description: "Viên các loại, đậu phụ, xúc xích xiên que ngâm sốt cay đặc trưng — món ăn vặt hot trend.",
    ingredients: ["Viên các loại", "Đậu phụ", "Xúc xích", "Sốt cay"],
    image: "/images/foods/xien-ban.jpg",
    fallbackImage: fallbackImages.hotpot,
  },
  {
    id: "xoi-com",
    name: "Xôi cốm",
    tag: "Sáng / Ăn nhẹ",
    price: 20000,
    calories: 380,
    time: "5 phút",
    rating: 4.6,
    description: "Xôi cốm xanh mướt, dẻo thơm mùi lá dứa, ăn kèm dừa bào và đường.",
    ingredients: ["Cốm", "Gạo nếp", "Dừa bào", "Đường"],
    image: "/images/foods/xoi-com.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "xoi-ga",
    name: "Xôi gà",
    tag: "Sáng / Trưa",
    price: 30000,
    calories: 650,
    time: "7 phút",
    rating: 4.7,
    description: "Xôi nếp ăn cùng thịt gà xé, hành phi, rau răm và nước sốt.",
    ingredients: ["Gạo nếp", "Thịt gà", "Hành phi", "Rau răm"],
    image: "/images/foods/xoi-ga.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "xoi-lac",
    name: "Xôi lạc",
    tag: "Sáng",
    price: 15000,
    calories: 530,
    time: "5 phút",
    rating: 4.4,
    description: "Xôi nếp trộn lạc rang, vừa dẻo vừa bùi, ăn kèm muối vừng hoặc ruốc.",
    ingredients: ["Gạo nếp", "Lạc", "Muối vừng"],
    image: "/images/foods/xoi-lac.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "xoi-tom",
    name: "Xôi tôm",
    tag: "Sáng / Trưa",
    price: 40000,
    calories: 620,
    time: "8 phút",
    rating: 4.7,
    description: "Xôi nếp dẻo ăn cùng tôm khô, hành phi giòn, ruốc và nước mắm pha.",
    ingredients: ["Gạo nếp", "Tôm khô", "Hành phi", "Ruốc"],
    image: "/images/foods/xoi-tom.jpg",
    fallbackImage: fallbackImages.rice,
  },
  {
    id: "xoi-xeo",
    name: "Xôi xéo",
    tag: "Sáng",
    price: 15000,
    calories: 520,
    time: "5 phút",
    rating: 4.6,
    description: "Xôi nếp dẻo ăn với đậu xanh, hành phi và mỡ hành.",
    ingredients: ["Gạo nếp", "Đậu xanh", "Hành phi", "Mỡ hành"],
    image: "/images/foods/xoi-xeo.jpg",
    fallbackImage: fallbackImages.rice,
  },
];
